### ISSUE TITLE
Restructure geofences accordion

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-frontend#134]
- [x] Create necessary sublevels
- [x] Restructure handlers for buttons / autocomplete for new data structure.
- [x] Automate the option type classification (if it's a button, and autocomplete or what)

**Comment by danflop** [comment]
Acceptance Criteria: the accordion menu is fully restructured according to the options discussed, showing buttons and autocomplete fields.

**Comment by alegnaaived** [comment]
Changing aceptance criteria:
OLD:
- [ ] Define handlers for buttons / autocomplete options that logs something (for now).
NEW:
- [ ] Restructure handlers for buttons / autocomplete for new data structure.
