### ISSUE TITLE
Load Ecosystems graphics when the option is selected

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-frontend#139]
When an user goes to Consultas --> Geofence Option --> Ecosistemas tab

![image.png](https://images.zenhubusercontent.com/5898844951aa2c3057739338/03cb17b7-4e27-4bdf-a2d4-331956557ee6)

The next information should load on the tab:

1. Graphic (Area percentage and Ha per strategic ecosystems: Bosque seco, páramos y humedales).
2. Graphic (Ecosystem percentage per Protected area per category).
3. Cover type percentage (Natural and transformed).

This information could be loaded using endpoints implemented by @erikasv here https://github.com/PEM-Humboldt/biotablero-backend/issues/60

**Comment by danflop** [comment]
Acceptance Criteria: When the user selects a geofence option and then the Ecosystem tabs, the graphics discussed should load using the endpoints.

**Comment by danflop** [comment]
Sort in the right order and graphics could change

**Comment by alegnaaived** [comment]
Sorted in the right order.

![Captura de pantalla de 2019-03-19 13-50-12.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/ee5e3bf4-010d-405c-8e70-e12a4a470b30)
