### ISSUE TITLE
Implementar filtros

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#140]
### Descripción
Conectar el panel de los filtros con la búsqueda de los indicadores correspondientes. Esta conexión se debe hacer enviando las consultas correspondientes al backend.

### Resultado
Al seleccionar filtros, las tarjetas que se muestran son aquellas que tienen los tags seleccionados.

### Consideraciones
A pesar de que la lista de tags parece fija, la misma se debe cargar desde el backend.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/140?planning-poker) with ZenHub @alegnaaived @danflop @Trjegul84

**Comment by erikasv** [comment]
Dudas o cuestiones importantes que salieron durante la implementación:

- El backend tiene una limitante de 10 filtros, se desea que se puedan aplicar más de 10 filtros?
- Los filtros funcionan con `OR`, es decir se listan todos los indicadores que tengan cualquiera de los filtros. El backend no permite aplicar esta condición con un `AND`
- El botón del panel de filtros está ocultando todo cuando se presiona, debe ser así o debería ocultar sólo las opciones disponibles (y dejar los filtros ya seleccionados)
