### ISSUE TITLE
Geofence overview

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#163]
### Description:
The first component for representative data per search selected area.

### Acceptance criteria:
- [x] Show total ha by selected area ( = search area) and percentage
- [x] Show ha sum of all strategic ecosystems by selected area and percentage in this selected area
- [ ] Add graph coverage N/T by geofence
- [ ] Add graph AP/NP by geofence

**Comment by erikasv** [comment]
This issue is in "Done", I'm closing it to close the milestone. If it needs to be reopened assign another milestone.
