### ISSUE TITLE
Extraer funcionalidades clickFeature, highlightFeature, y resetHighlight de Compensation y Search

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#186]
## Descripción:
Extraer las funcionalidades de los componentes Compensation y Search relacionados a la manipulación de la capa hacia un componente independiente para ser reusado por otros componentes.

### Resultado:
 - Componente con información reusable de las acciones de usuario sobre el mapa, que son resaltar el mapa (highlightFeature), hacer clic en el mapa (clickFeature) y cambiar de foco en el mapa (resetHighlight)

### Endpoints relacionados con esta tarea:
 - Ninguno

## Consideraciones:
- Nuevos componentes funcionales creados
- Funciones de mapa removidas de los componentes Compensation y Search
- Las modificaciones no deben afectar las interacciones del usuario con el Front-End

**Comment by cazapatamar** [comment]
Se trabajará por medio de la tarea [#200](https://app.zenhub.com/workspaces/biotablero-5c423842116ade5d16d9d425/issues/pem-humboldt/biotablero-frontend/200)
