### ISSUE TITLE
(Cambiar nombre) Extraer funcionalidades de organización de información en Compensation y Search

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#194]
## Descripción:
Extraer las funcionalidades de organización de información entre el mapa y el menú lateral para ser reusado entre componentes.

### Resultado:
Componente nuevo con los helpers relacionados a la organización de la información y que sea coherente entre los endpoints para mapa y para menús laterales, que sean producto de refactor como: organizar estructuras de datos para mapas y menús laterales

### Endpoints relacionados con esta tarea:
- Ninguno

## Consideraciones:
- Nuevos componentes funcionales creados
- Nuevo componente funcional importado en los componentes Compensation y Search
- Las modificaciones no deben afectar las interacciones del usuario con el Front-End

**Comment by alegnaaived** [comment]
Ejemplo de referencia para futuros ajustes a esta tarea, para ser redactada de forma que indique cómo lograr datos más estandarizados del Back-end al Front-end:
![image](https://user-images.githubusercontent.com/15584917/84418319-a2296c80-abdc-11ea-88fa-475d15ed1930.png)

**Comment by erikasv** [comment]
@cazapatamar , @danflop , @alegnaaived , @Trjegul84 Debido a la diversidad en la información y funcionalidades que hemos visto con la introducción de Huella Humana y Bosques, creo que no es apropiado tratar de generalizar estos componentes.

Adicionalmente la información de ejemplo puesta en el comentario ya no existe, entonces no sé qué podríamos tomar de referencia.

**Comment by cazapatamar** [comment]
Con huella humana y bosques Compensation y Search han tomado rumbos distintos. De acuerdo en no generalizar y modificar Compensation que hasta el momento funciona bien para lo que fue creado.
