### ISSUE TITLE
Gráfico para visualizar el valor promedio de la huella humana para el año más reciente discriminado por categoría

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#198]
## Descripción:
Crear gráfica tipo barra horizontal apilada que mostrará la proporción de cada categoría para el año más reciente: Natural (0-15), Baja (15-30), Media (30-60), Alta (60-100). Lo anterior se visualizará de la misma manera como se muestra actualmente la proporción de coberturas.

![Grafica.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/09d760aa-d0c3-4260-8de7-f2b9864d9414)

### Resultado:

- Gráfico que permita visualizar el valor promedio de la huella humana en el año más reciente

### Endpoints relacionados con esta tarea:
Ninguno

## Consideraciones:
 - Crear el gráfico con datos de prueba usando un mockup en el front con la misma estructura de como llegarían los datos del API.
 - Verificar los colores para este gráfico con César, para crear dentro de la función de colores (matchColor) la paleta de colores correspondiente a este gráfico.

**Comment by alegnaaived** [comment]
Requiero ayuda para que los colores del gráfico anterior y el nuevo coincidan:
![image](https://user-images.githubusercontent.com/15584917/81517730-7aa36380-9301-11ea-8910-e8ab0116daaa.png)
