### ISSUE TITLE
Gráfica de lineas para HF en el tiempo en la unidad de consulta y ecosistemas estratégicos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#201]
## Descripción:
Implementar un gráfico de líneas que permita mostrar 4 líneas con relación al promedio del índice de huella humana en los diferentes períodos de tiempo, una para los valores en la unidad de consulta y las otras 3 para los valores en los ecosistemas estratégicos dentro de la unidad de consulta.

En la gráfica se debe poder seleccionar un ecosistema estratégico por medio de un botón externo ([toggle](https://material-ui.com/components/toggle-button/#toggle-buttons)), esta interacción va a estar relacionada con cambios en el mapa y en el texto de la tarea [203](https://github.com/PEM-Humboldt/biotablero-frontend/issues/203), por lo tanto es importante que de dicha interacción se extraiga el identificador del ecosistema estratégico.

En la gráfica se deben visualizar unas lineas de fondo, paralelas al eje x, que representan los puntos de cambio entre categorías: 15 (de natural a baja), 30 (de baja a media) y 60 (de media a alta).

### Resultado:
Gráfica similar a [esta](https://vx-demo.now.sh/glyphs). Sobre la cual se pueda seleccionar un ecosistema estrátegico, ya se de forma directa con el gráfico o por medio de un elemento externo.

### Endpoints relacionados con esta tarea:
Utilizar mockups

## Consideraciones:
* La gráfica acordada será la implementada en el ejemplo realizado por @cazapatamar
* Indispensable que al seleccionar un ecosistema estratégico se obtenga un identificador del mismo para poder consultar más información (interactuar con el mapa y el texto de la tarea [203](https://github.com/PEM-Humboldt/biotablero-frontend/issues/203))
* No conectar las interacciones de las líneas con el mapa ni con el texto debajo de la gráfica, para esto hay dos tareas separadas (para que tanto la revisión como el desarrollo en sí mismo sea más modular).
 * Verificar los colores para este gráfico con César, para crear dentro de la función de colores (matchColor) la paleta de colores correspondiente a este gráfico.

**Comment by alegnaaived** [comment]
He avanzado al implementar la gráfica de líneas en NIVO, logrando el siguiente avance:

![image](https://user-images.githubusercontent.com/15584917/81584174-0657d700-9378-11ea-91c7-275a768f4e1c.png)

Se identifica que se requiere analizar el impacto en la función matchColor, se necesita capturar los eventos del mouse para gestionar la transición tanto en el gráfico como hacia el mapa.

**Comment by alegnaaived** [comment]
A cierre del Sprint 3, hace falta cargar el branch con las correcciones solicitadas y pasar por revisión del branch en GitHub
