### ISSUE TITLE
Activar / desactivar capas de ecosistemas en unidad de consulta al seleccionar / de-seleccionar ecosistemas en gráfica de HF a través del tiempo

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#202]
## Descripción:
Conectar las acciones de los botones que permiten activar ecosistemas en la gráfica de líneas con las capas que se activan o desactivan en el mapa.

### Resultado:
Funcionalidad de activar/desactivar capa en el mapa al seleccionar/de-seleccionar un ecosistema.
- [ ] Cuando un ecosistema se selecciona en la gráfica, se debe activar la capa en la unidad de consulta, correspondiente al ecosistema seleccionado.
- [ ] Si la capa de otro ecosistema está activa al momento de seleccionar el ecosistema, esa capa se debe desactivar.
- [ ] Si el ecosistema se "de-selecciona" la capa correspondiente debe desactivarse.

### Endpoints relacionados con esta tarea:
Resultados de la tarea [131](https://github.com/PEM-Humboldt/biotablero-backend/issues/131)
* /ea/:ea_id/se/:se_type/layer
* /pa/:pa_id/se/:se_type/layer
* /states/:state_id/se/:se_type/layer
* /basinSubzones/:subzone_id/se/:se_type/layer

**Comment by alegnaaived** [comment]
En el Sprint 4 se avanzó el mockup de las geometrías de cada ecosistemas estratégicos y se identificó los eventos y estados para elegir la capa activa y de-seleccionar la capa al cambiar de vista.

**Comment by alegnaaived** [comment]
La tarea [131](https://github.com/PEM-Humboldt/biotablero-backend/issues/131) aún está pendiente por ser desarrollada. Se creó el mockup tmp_hf_timeline_geo.json

**Comment by alegnaaived** [comment]
En el Sprint 5 se implementó un mockup a una única respuesta. Se debe cambiar el comportamiento para solicitar un ecosistema particular, no todos los ecosistemas estratégicos en la huella humana en el tiempo

**Comment by danflop** [comment]
Se crea tarea #305 para continuar con la implementación.
