### ISSUE TITLE
Interacción bidireccional de la gráfica de persistencia de huella humana con el mapa de persistencia

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#208]
## Descripción:
Implementar la interacción bidireccional de la gráfica de persistencia de la huella humana con su respectivo mapa. Es decir, al hacer clic en alguna categoría (geometría) en el mapa, se resaltará en el mapa y a la vez se resaltará su correspondiente sección en la gráfica de la barra horizontal de persisitencia.

### Resultado:
Interacción bidireccional de la gráfica de persistencia de la huella humana con el mapa de persisitencia.

### Endpoints relacionados con esta tarea:
Ninguno relacionado.

## Consideraciones:
En caso de que no sea posible resaltar el color en la barra se tiene la alternativa de mostrar un tooltip al tiempo, tanto sobre el mapa como sobre el gráfico.

**Comment by cazapatamar** [comment]
Solucionado en el PR [#301](https://github.com/PEM-Humboldt/biotablero-frontend/pull/301)

**Comment by cazapatamar** [comment]
Se dejó únicamente interacción unidireccional de gráfico a mapa.
