### ISSUE TITLE
Gráficas Biomas y Regiones Bióticas migrada a NIVO

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#234]
## Descripción:
Disminuir tamaño para gráficas Biomas y Regiones Bióticas para resaltar la de Factor de compensación la cual se debe mostrar de primeras usando la libreria NIVO.

### Resultado:
Las gráficas Biomas y Regiones Bióticas migradas a NIVO

### Endpoints relacionados con esta tarea:
Los endpoints usados en las gráficas actuales para Biomas y Regiones Bióticas

## Consideraciones:
Utilizar los endpoints que están siendo usados por el componente SmallBarStack

**Comment by cazapatamar** [comment]
Tarea hecha por medio de este pull request

https://github.com/PEM-Humboldt/biotablero-frontend/pull/245
