### ISSUE TITLE
Migración NIVO

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#235]
## Descripción:
Implementar los gráficos actuales y nuevos, usando la librería NIVO https://nivo.rocks/

### Resultado:
Los gráficos están implementados en NIVO y la librería VX no es una dependencia del proyecto.

### Endpoints relacionados con esta tarea:
(Múltiples)

## Consideraciones:
Usar npm para desinstalar VX de las dependencias del proyecto. Verificar el package.json y package-lock.json

**Comment by erikasv** [comment]
Es probable que nunca se realice la migración en compensaciones. Si en algún momento resulta necesario, se creará una nueva epica.
