### ISSUE TITLE
Conectar endpoints a Frame (caja en segundo nivel) de persistencia de Huella Humana

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#239]
## Descripción:
En la pestaña "Paisaje" para gráfica horizontal acumulada, conectar a través de RestAPI el gráfico con los endpoints del siguiente issue: https://github.com/PEM-Humboldt/biotablero-backend/issues/133

### Resultado:
Mockups eliminados y endpoints conectados

### Endpoints relacionados con esta tarea:
https://github.com/PEM-Humboldt/biotablero-backend/issues/133

## Consideraciones:
Verificar la eliminación de los mockups

**Comment by cazapatamar** [comment]
Solucionada en #309
