### ISSUE TITLE
Conectar el gráfico para visualizar el valor promedio de la huella humana con endpoint

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#240]
## Descripción:
Para el gráfico para visualizar el valor promedio de la huella humana para el año más reciente discriminado por categoría, reemplazar el mockup por la implementación en el RestAPI de la conexión con el endpoint https://app.zenhub.com/workspaces/biotablero-5c423842116ade5d16d9d425/issues/pem-humboldt/biotablero-backend/123. Luego, eliminar el mockup usado en esta gráfica.

### Resultado:
Mockup eliminado y endpoint conectado al gráfico

### Endpoints relacionados con esta tarea:
https://app.zenhub.com/workspaces/biotablero-5c423842116ade5d16d9d425/issues/pem-humboldt/biotablero-backend/123

## Consideraciones:
Verificar la eliminación del mockup.

**Comment by cazapatamar** [comment]
Solucionada en #309
