### ISSUE TITLE
Tamaño responsivo para los gráficos con NIVO

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#248]
## Descripción:

La librería NIVO posee el mismo problema que la librería VX: El comportamiento del tamaño de los gráficos es definido por el componente que los contiene. Actualmente, usamos de la librería VX el componente responsive para enviar al gráfico el tamaño que debe tener el gráfico y que se redimensione de acuerdo a la pantalla en que se visualiza. La idea es identificar que hay forma de dejar de usar ese componente de la librería VX y cambiarlo por otra librería, buscando un comportamiento fluído, que se pueda eliminar una de las dependencias y que se evite o se mejore la implementación del componente RenderGraph.

### Resultado:

Definir si seguir usando responsive de VX o si se puede usar una la mejor alternativa para el tamaño responsivo de los gráficos.

### Endpoints relacionados con esta tarea:
Ninguno.

**Comment by cazapatamar** [comment]
Se concluye que no es necesario renderizar los gráficos nuevos a través de RenderGraph, es decir, los que están implementados con NIVO, sino que se puede hacer el llamado directo sobre GraphLoader para gráficar y de esta forma evitar usar el componente "parent" de VX.

Se realiza este cambio para las gráficas implementadas hasta el momento con NIVO (LargeBarStackGraph y SmallBarStackGraph), dejando que el ancho sea asignado por la característica responsive inherente a los gráficos de esta librería y renderizando a través de GraphLoader.
