### ISSUE TITLE
Interacciones en la gráfica de Huella Humana en el tiempo

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#254]
## Descripción:
La gráfica de líneas de la [huella humana en el tiempo](https://github.com/PEM-Humboldt/biotablero-frontend/issues/201) debe interactuar con sí misma de la forma en la que describe en el [documento de visualización](https://docs.google.com/document/d/1QQLmXMvVXlZ5fBHdimPiroBzDXsT50Pqk5ygk0DKV9s/edit#heading=h.tcukwudjs7gs).

Es decir, al seleccionar un ecosistema estratégico se deben atenuar las gráficas de los demás ecosistemas.

### Resultado:
La interacción de la gráfica en sí misma.

### Endpoints relacionados con esta tarea:
Ninguno.

## Consideraciones:
La idea es intentar hacer esto a través de la leyenda de la gráfica, pero en caso de que no sea posible, buscar una alternativa como botones externos y repintar todo el gráfico

**Comment by alegnaaived** [comment]
A cierre del Sprint 3, hace falta cargar el branch y pasar por revisión del branch en GitHub

**Comment by alegnaaived** [comment]
Llamar desde el componente GraphLoader y remover uso de RenderGraph
