### ISSUE TITLE
RenderGraph eliminado dada la migración a NIVO

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#271]
## Descripción:
Eliminar componente RenderGraph del código fuente luego de realizar la migración de todas las gráficas a NIVO

### Resultado:
Componente RenderGraph eliminado

## Consideraciones:
Antes de eliminar confirmar que no tiene ningún otro llamado

**Comment by erikasv** [comment]
Se realizó la separación de los componentes de Consultas y Compensaciones, también se decidió que no se realizarán migraciones o actualizaciones en Compensaciones
