### ISSUE TITLE
Migrar el arreglo "colors" de Compensation

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#281]
## Descripción:
Se realizó la creación de la paleta de colores 'eqEcoCompensation' y se asumió un comportamiento similar a la paleta 'se', pero en la estructura switch se debe tener una lógica similar a la del caso 'fc', para filtrar el valor de consulta entre uno de los rangos de valores y agrupando resultados en una de las categorias. Los rangos de colores están en el estado 'colors' y en la lógica dentro del componente 'Compensation'.

Actualmente, la aplicación funciona usando el estado 'colors' en el componente 'Compensation', pero tiene un error que se presenta en consola ya que la lógica de la función 'matchColor' no está implementada correctamente para reemplazar en la lógica de 'Compensation' y requiere ajustes para completar la migración.

### Resultado:
'Compensation' utiliza la funcion 'matchColors' y la paleta 'eqEcoCompensation', y se elimina el arreglo 'colors' del estado en el componente 'Compensation'.

### Endpoints relacionados con esta tarea:
Ninguno.

## Consideraciones:
Verificar que no se presente la alerta por el tipo incorrecto de datos en Drawer:
![image.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/427b3b24-eaf8-425b-b07a-a4012f8ff53a)

**Comment by erikasv** [comment]
La creación de la paleta se deshizo para no dejar código que no está siendo utilizado o con errores en la aplicación. Hay que cambiar todo el objetivo y descripción de esta tarea o cerrarla y crear una nueva. El verdadero objetivo es usar matchColor desde el módulo de compensaciones.

**Comment by cazapatamar** [comment]
De acuerdo en crear una nueva tarea para usar matchColor en compensaciones pero no sé qué tan prioritario sea hacer ese cambio en este momento.
