### ISSUE TITLE
Bug: Revisar error en la consola al cargar pestaña paisaje

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#282]
## Descripción:
Actualmente está pareciendo un error en la consola al abrir la pestaña Paisaje, relacionado con un key único de las 3 gráficas de Factor de Compensación. Revisar y hacer seguimiento a este error para encontrar una solución que posiblemente pueda estar al ajustar el método que realiza la transformación de los datos para la gráfica LargeBarStackGraph

### Resultado:
Error no aparezca en consola al cargar pestaña paisaje

**Comment by cazapatamar** [comment]
Solucionado en [PR 288](https://github.com/PEM-Humboldt/biotablero-frontend/pull/288)

**Comment by erikasv** [comment]
No estaba relacionado con las gráficas sino con un array para colocar los diferentes componentes del acordeón interno de factor de compensación.
