### ISSUE TITLE
Optimizar creación de componentes en acordeones

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#290]
## Descripción:
Evitar crear todos los componentes de los acordeones desde los componentes padres porque se están renderizando muchas veces aunque no sean visibles y además hacen peticiones innecesarias.

### Resultado:
Los componentes de los acordeones se renderizan sólo cuando son visibles

**Comment by erikasv** [comment]
Esto se debería resolver con una propiedad en componente Accordion de Material-UI (actualización del ExpansionPanel que tenemos actualmente)

**Comment by cazapatamar** [comment]
Solucionada en #308
