### ISSUE TITLE
Cargar la geometría de la geocerca al seleccionar área de consulta

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#296]
## Descripción:
Cargar la geometría de la geocerca al estar sobre la pestaña "Ecosistemas" una vez se haya seleccionado el área de consulta en el Selector. Esta geometría es básica, únicamente para relacionar las gráficas de la pestaña de ecosistemas y el mapa.

### Resultado:
Geometría de la geocerca al seleccionar el área de consulta

### Endpoints relacionados con esta tarea:
Desarrollados en la tarea [147](https://github.com/PEM-Humboldt/biotablero-backend/issues/147):
* /basinSubzones/layers/:subzone_id (SubzoneLayer)
* /ea/layers/:ea_id (EALayer)
* /pa/layers/:category (CategoryLayer)
* /states/layers/:state_id (StateLayer)

## Consideraciones:
Tener en cuenta las interacciones entre las pestañas Ecosistemas, Paisaje y Especies. La idea es que la capa de esta tarea quede por defecto y sólo se cambie cuando se accede a la pestaña paisaje.

**Comment by alegnaaived** [comment]
En el Daily de hoy se definió que abra esta geometría si no está ninguna geometría específica definida
