### ISSUE TITLE
Spike: Componente tipo modal en Mapviewer para cuando carga el mapa

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#300]
## Descripción:
Investigar que componente puede reemplazar el modal que se despliega actualmente mientras carga el mapa ya que este captura el foco de toda la página y no deja interacturar con otros componentes. Revisar si hay algún otro componente tipo modal o de otro tipo que permita mostrar la sección de "cargando ..." sin capturar todo el foco de la página.

### Resultado:
Componente para reemplazar el modal actual que se muestra mientras cargan los datos del mapa

**Comment by alegnaaived** [comment]
Alternativas por comenzar a revisar:
 - https://www.basefactor.com/react-how-to-display-a-loading-indicator-on-fetch-calls
 - https://github.com/derrickpelletier/react-loading-overlay
 - https://medium.com/front-end-weekly/react-loading-screen-tactics-improving-user-experience-9452f183c00b

**Comment by alegnaaived** [comment]
Evaluar si la versión de Material-UI es la que restringe el uso de la bandera mencionada. https://material-ui.com/es/components/modal/#modal
