### ISSUE TITLE
 Carga de capa seleccionada en lugar de una única capa con información de ecosistemas estratégicos 

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#305]
## Descripción:
La tarea #202 implementó un mockup que trae en una única respuesta la información de todos los ecosistemas estratégicos en un área de consulta. Esta funcionalidad debería implementarse por ecosistema estratégico.

### Resultado:
- Realizar cuatro llamados diferentes: Area total, Páramo, Humedal, Bosque seco
- Reemplazar implementación de mockup único por llamados a los endpoints de la tarea [#131 ](https://github.com/PEM-Humboldt/biotablero-backend/issues/131) por cada ecosistema estratégico y para el área total

### Endpoints relacionados con esta tarea:
/ea/:ea_id/se/layers/:se_type
/pa/:pa_id/se/layers/:se_type
/states/:state_id/se/layers/:se_type
/basinSubzones/:subzone_id/se/layers/:se_type

## Consideraciones:
Cada ecosistema debe ser una capa aparte

**Comment by erikasv** [comment]
@danflop @cazapatamar @alegnaaived 

Algo que nos faltó de esta tarea es que se está cargando el mapa que no es, recuerden que para esta gráfica se debe cargar el mapa de persistencia. Entonces sería agregar ese ajuste a esta tarea.

Otra cosa: en la descripción dice que hay que realizar 4 llamados diferentes, y no es así, son sólo 3 para los ecosistemas estratégicos, para el área total no hay que hacer ningún llamado

**Comment by erikasv** [comment]
También actualicé la tarea:
* El enlace a la tarea del backend estaba mal (apuntaba a un issue del front)
* Cambié los endpoints para que se ajustaran más a la estructura actual

**Comment by alegnaaived** [comment]
Se acuerda en Daily aclarar la interacción con la capa base del gráfico de línea de tiempo de huella humana con César y actualizar el documento de Visualización (tarea ya asignada).
