### ISSUE TITLE
Actualizar componente ExpansionPanel a Accordion

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-frontend#308]
## Descripción:
En alguna versión de material-ui ExpansionPanel cambió a Accordion, y para optimizar las peticiones que se hacen desde todas las secciones de Paisaje, necesitamos actualizar el componente para utilizar la propiedad [TransitionProps](https://material-ui.com/components/accordion/#performance)

### Resultado:
Ahora se usa el componente Accordion e idealmente se usa la propiedad TransitionProps para destruir los compoenentes de los paneles ocultos

### Endpoints relacionados con esta tarea:
Ninguno

## Consideraciones:
Si la propiedad TransitionProps no funciona como es esperado, dedicarle el máximo de tiempo estimado y crear otra tarea para optimizar esas cargas

**Comment by cazapatamar** [comment]
Se realiza una primera revisión de migración del componente ExpansionPanel a Accordion, lo cual es viable y no representa mayor cambio en la funcionalidad actual. Sin embargo, se encuentra que para usar este componente es necesario subir la versión de @material-ui/core de 3.9.2 a 4.0.11, lo cual tiene un alto impacto en otros componentes de Biotablero que dependen de esta librería. Por otro lado, la tarea para manejar la interacción entre acordiones y mapa fue completada sin necesidad de migrar el componente accordion. 

Por lo tanto, se cambia la prioridad de esta tarea a baja y se sugiere cambiar el alcance para que se realice toda la migración de Material UI a 4.11.0.

**Comment by cazapatamar** [comment]
Solucionado en PR https://github.com/PEM-Humboldt/biotablero-frontend/pull/385
