### ISSUE TITLE
Verificar respuestas en consola cuando se carga un tipo de geometría

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#317]
## Descripción:
Cuando se selecciona un tipo de geometría (por ejemplo, "Departamentos") en el selector, se está generando un error 500. Además, se produce este error y se debe encontrar solución https://github.com/PEM-Humboldt/biotablero-frontend/pull/310#issuecomment-661945924

### Resultado:
Se identifica las causas de los dos errores, para corrijirlos, capturarlos o planear más tareas.

### Endpoints relacionados con esta tarea:
Ninguno

## Consideraciones:
Se crea esta tarea a partir de este comentario https://github.com/PEM-Humboldt/biotablero-frontend/pull/310#issuecomment-660352373 y https://github.com/PEM-Humboldt/biotablero-frontend/pull/310#issuecomment-661945924

**Comment by alegnaaived** [comment]
Para error 500, revisar si todas las peticiones se están respondiendo.

**Comment by alegnaaived** [comment]
Se identificó el error de carga de capas, que tiene que ver con la transición entre el selector de área y abrir la pestaña paisajes antes que el mapa de Colombia dividido en las áreas sea cargado. El resultado al probar las transiciones entre selector y pestaña paisajes fue:
 ![image](https://user-images.githubusercontent.com/15584917/88851523-7e34e100-d1b2-11ea-9c2b-6e87537d8260.png)

Para el [issue sobre Landscape](https://github.com/PEM-Humboldt/biotablero-frontend/pull/310#issuecomment-661945924), no fue posible replicar el error

**Comment by erikasv** [comment]
Volví a revisar ambos casos descritos en los comentario, pero ninguno se logró replicar. Se da por cerrada esta tarea ya que  han habido muchos cambios que afectan los flujos que causaban estos errores y si llegan a volver a ocurrir se debe volver a investigar el caso.
