### ISSUE TITLE
Ajustar el método del tooltip en el mapa para incluir caso particular de geometrías a nivel nacional

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#322]
## Descripción:
El error ocurre desde el módulo consultas. El caso de ejemplo fue el siguiente: Se selecciona como área de consultas "Departamentos" y luego "Putumayo". Carga la información de las pestañas el mapa de "Departamentos". 

![image.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/868dc8f4-db79-45f3-beaa-2f7a65a4e490)

Al ubicar el cursor sobre el mapa, se obtiene el siguiente error:

![image.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/bd89fe03-001d-4868-b868-7e32e12dde90)

### Resultado:
Cambio de capa controlado: Se detiene la petición de la geometría "Departamentos" cuando está seleccionada un área de consulta de las opciones listadas dentro de departamentos u otro tipo de área de consulta.

## Consideraciones:
Se debe revisar el error de la imagen, dado que no todos los eventos de resaltar una capa están siendo manejados.

**Comment by cazapatamar** [comment]
El error se presenta cuando se pasa el mouse sobre la geometría que se carga inicialmente al seleccionar el tipo de área de consulta, por ejemplo, cuando se selecciona "Departamentos", se carga el mapa de todo el país dividido por departamentos en color rosado.

Dado que se modificó el método del tooltip para incluir toda la lógica de huella humana, no se tuvo en cuenta este caso particular dado que para las capas de HH se incluyó un atributo type, el cual determina que información se muestra en el tooltip.

Le cambiaré el titulo a la tarea para que sea mas claro el error.
