### ISSUE TITLE
Error en transición con componente EcosystemBox

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#323]
## Descripción:
Al seleccionar un área de consulta y realizar cambio de pestañas entre ecosistemas, paisajes y especies, y regresar a ecosistemas, se está obteniendo el siguiente error en consola:

![image.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/d5cc2100-676d-4dd3-9f90-6387ea1b61f9)

### Resultado:
Se identifica los eventos que originan el error y se maneja el evento para que no vuelva a aparecer este error en consola.

### Endpoints relacionados con esta tarea:
No se identifican relacionados.

**Comment by cazapatamar** [comment]
No pude replicar el error estando sobre la rama de los últimos cambios que subió Erika donde se hizo un refactor de las peticiones y mejoras en los componentes (feature/encapsulateSections
a1fb553). El error te aparece trabajando sobre develop?
