### ISSUE TITLE
Error al cambiar mapa desde ecosistema estratégico dentro de huella humana

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-frontend#326]
## Descripción:
La siguiente es la explicación para reproducir el error:
  Se está consultando huella humana en el tiempo y se ha seleccionado un ecosistema estratégico. Se utiliza el botón de regresar y se selecciona otra área de consulta. Es ahí cuando se genera el siguiente error:

![image.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/b805c671-2c4a-4386-8cbc-673fae8465e8)

### Resultado:
La navegación desde el área de consulta seleccionada con mapa de ecosistema estratégico hacia otra área de consulta no genera error.

### Endpoints relacionados con esta tarea:
No se identifican.

**Comment by danflop** [comment]
No fue posible reproducirlo y ya se han realizado muchos campos sobre los componentes involucrados.
