### ISSUE TITLE
Revisión de estilos y detalles visuales del front

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#330]
## Descripción:
Revisar los estilos actuales en el front y prestar especial atención a los siguientes puntos:

1- Mejorar el fondo de la barra con área total de la unidad de consulta (título "hectáreas totales") (depronto que toda la barra sea negra)
2- Ubicación del botón de información en todos los paneles del acordeón de huella humana (aparece abajo, pero debería estar al lado del nombre de la sección como en la sección de FC y Biomas)
3- Dar formato al color de fondo del valor de huella humana actual (promedio) en la unidad de consulta para que sea acorde a la categoría en la que se encuentra ese valor
4- Interacción de grafica a mapa para capa de factor de compensación?
5- Textos HF

**Comment by cazapatamar** [comment]
3. Para punto 3, se ajusto el endpoint que trae valor de huella humana actual para que tambien retorne la categoria #164
