### ISSUE TITLE
Actualizar versión de Material UI

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#339]
## Descripción:
Actualizar vesión de Material UI y analizar que componentes se ven afectados (por ejemplo el Selector). Cambiar o actualizar los componentes para poder realizar la migración completa y si es necesario aumentar el tiempo estimado.

### Resultado:
Material UI actualizado a la última versión donde los componentes actuales que dependen de la librería funcionen correctamente.

**Comment by alegnaaived** [comment]
Documento de avance sobre esta tarea: https://docs.google.com/document/d/14iee4yOrhQHSviuLtgCeKUGorx02wI5zYsrLsApMEvA/edit?usp=sharing

Enlaces consultados:
https://material-ui.com/es/guides/migration-v3/#update-material-ui-styles-version
https://material-ui.com/components/text-fields/#integration-with-3rd-party-input-libraries
https://codesandbox.io/s/dbfz3?file=/demo.js:547-561
https://material-ui.com/es/api/chip/

**Comment by cazapatamar** [comment]
@Trjegul84 Mira Angela, este fue el avance que tuvo Angela Devia en su momento.

**Comment by cazapatamar** [comment]
Solucionado en PR https://github.com/PEM-Humboldt/biotablero-frontend/pull/385
