### ISSUE TITLE
Estandarizar locale para los decimales

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#360]
## Descripción:
Los puntos decimales (.) de los valores de los tooltips de las gráficas están siendo cambiados por comas (,) pero las comas de las unidades de mil no están siendo cambiadas.

Además los valores de los ejes de las gráficas no toman dicho cambio.

### Resultado:
- [X] Tomar esta decisión con Cesar y Jaime
- [ ] Estandarizar los separadores decimales en todas las gráficas y ejes

## Consideraciones:
Tomar esta decisión con Cesar y Jaime

**Comment by cazapatamar** [comment]
Se estableció que la mejor alternativa es espacios para miles/millones y punto para decimales. Si no se encuentra la forma de implementar esta opción entonces dejarlo con comas para miles/millones y puntos para decimales.

**Comment by danflop** [comment]
Queda comas para miles/millones y puntos para decimales.
