### ISSUE TITLE
Spike: Treemap para datos de integridad

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-frontend#362]
## Descripción: 
Hacer pruebas sobre el treemap de NIVO. En caso de que no se cumplan las expectativas buscar alternativas y discutir con Jaime y Cesar.

### Resultado:
Tener un gráfico decidido para la sección 2 de Bosques

**Comment by erikasv** [comment]
Conclusiones:

La forma en la que se va a mostrar la información es la siguiente:
* El primer nivel, es decir las categorías de SCI y HH, se muestran en una dona como la del ejemplo en [nivo](https://nivo.rocks/pie)
* Cuando se le da clic a una categoría en la dona, se muestra una barra de distribución de áreas protegidas para esa categoría, como la que hay en la pestaña de ecosistemas

Se revisaron otras librerías, pero la integración de las mismas resulta muy compleja y no se lograría este año. La más opcionada a ser retomada es [tui-chart](https://ui.toast.com/tui-chart).

Se realizó un [PR](https://github.com/PEM-Humboldt/biotablero-frontend/pull/369) en medio de esta tarea al organizar código.
