### ISSUE TITLE
Spike: Determinar mejor opción para el gráfico de la sección 1 de Bosques.

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-frontend#363]
## Descripción:
Revisar si merece crear otro componente para que las cuatro barras queden en un solo gráfico o usar un grafico para cada barra.

### Resultado:
Tener decidido el gráfico a utilizar para esta sección.

**Comment by cazapatamar** [comment]
En esta tarea no se incluyó solo el spike si no también el desarrollo del componente. Se decidió implementar un componente de varias barras multiples, cada barra representa un periodo y cada barra tiene las 4 categorias, se definió la paleta de colores con Cesar. Se muestran los tooltips para cada categoría, con los label y colores de que aplican en cada caso. Los datos se traen por medio del endpoint para este fin y el cual por ahora tiene datos mock en el back.

Adicional, se implementó el valor en hectáreas de la persistencia de bosques para la geocerca seleccionada. Este dato se trae en otro endpoint con datos mock en el back.
