### ISSUE TITLE
Control para las geometrías inexistentes

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#377]
## Descripción:
Al acceder a la jurisdicción "Establecimiento Público Ambiental" (EPA) se genera un error en MapViewer: `Error: Bounds are not valid.`
Esto ocurre porque en la tabla `geo_environmental_authorities` no existe geometría para esta autoridad.

### Resultado:
Ya sea en Search o en MapViewer se controla cuando no hay geometría válida que cargar

### Endpoints relacionados con esta tarea:
Los de las capas para el mapa

## Consideraciones:
La autoridad "Departamento Administrativo Distrital del Medio Ambiente. (Santa Marta)" tampoco tiene geometría.
En ambos casos hay valores asociados en huella humana y probablemente en otros indicadores también.

**Comment by cazapatamar** [comment]
Solucionado con el PR #379
