### ISSUE TITLE
Migrar componente Autocomplete actual a Autocomplete de Material UI

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#383]
## Descripción:
Migrar componente Autocomplete actual a component Autocomplete de Material UI. Borrar el componente anterior y sus dependencias si no se están usando desde otros componentes. Implementarlo en el componente selector.

### Resultado:
Componente migrado usando Material UI.

## Consideraciones:
Primero realizar una prueba de implementación del componente Autocomplete de Material UI en la versión actual de biotablero (3.9.2) y ver si todas las funcionalidades son compatibles.

**Comment by Trjegul84** [comment]
Se reemplazaron los select por el componente Autocomplete de material UI en el selector del área de consultas y se arreglaron los estilos correspondientes.

**Comment by cazapatamar** [comment]
Solucionado en PR https://github.com/PEM-Humboldt/biotablero-frontend/pull/385

**Comment by Trjegul84** [comment]
Se terminarán los cambios en otra tarea #389 para trabajar sobre los componentes de compensaciones.
