### ISSUE TITLE
Agregar los headers de autenticación para el API

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#387]
## Descripción:
Agregar los headers de autenticación para el API

**Comment by erikasv** [comment]
@Trjegul84 @cazapatamar Se agregó el header de autenticación para las peticiones.

Pero toca hacer algunas modificaciones cuando se corre el gateway en modo desarrollo, ver las modificaciones correspondientes en: http://192.168.11.78/pem/biotablero_gateway/commit/688e1c42a689d7a2f802aed1dc04dc6079897708
