### ISSUE TITLE
Ocultar o deshabilitar sección pérdida y persistencia de bosque

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#388]
## Descripción:
Ocultar o deshabilitar sección pérdida y persistencia de bosque dado que los datos no están listos y posiblemente se demoren en ser entregados al equipo de desarrollo.

### Resultado:
Sección de perdida y persistencia oculta o deshabilitada

## Consideraciones:
Consultar con Jaime o Cesar cual es la mejor opción.

Revisar interacción.

**Comment by Trjegul84** [comment]
Se arreglaron los nombres de los atributos de componentsArray, ahora **_disabled_** se usa para efectivamente desactivar los acordeones (volverlos no visibles) y lo que antes llamábamos disabled ahora se llama _collapsed_ y sirve para expandir o colapsar un tab.   
Tanto collapsed como disabled serán opcionales  su valor por defecto será false. Si **collapsed** es verdadero, el tab no se expandirá y el primer tab que se carga será el primero que no tenga la propiedad collapsed. Para futuras ocasiones si se quiere deshabilitar cualquier tab (establecer disabled=true) se debe asignar true a collapsed (no expandido) de lo contrario no funcionará correctamente.
