### ISSUE TITLE
Reorganizar el código

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#390]
Reorganizar los componentes y módulos de acuerdo a la estructura [fractal](https://hackernoon.com/fractal-a-react-app-structure-for-infinite-scale-4dab943092af) o a alguna otra estrategia que tenga en cuenta la página de monitoreo como una aplicación independiente.

**Comment by erikasv** [comment]
Como parte de esta tarea se habilitó las rutas absolutas para babel, lo cual hace mucho más cómodo entender dónde está un archivo que con las rutas relativas, propongo que de ahora en adelante sólo usemos rutas absolutas (desde `src`) y los imports queden agrupados al menos por la carpeta principal (por ejemplo, primero todos los imports de `components` luego los de `utils` y luego los de `pages`, *en realidad el orden no importa, sólo que estén agrupados*)

que opinan? @cazapatamar @Trjegul84

**Comment by Trjegul84** [comment]
Con rutas absolutas desde el source te refieres a que las rutas absolutas deberán ir en todos los imports de todos los archivos que esten dentro de las subcarpetas de src y con rutas relativas como antes en todos los archivos de carpetas por fuera de source?

**Comment by cazapatamar** [comment]
Si, de acuerdo, me parece que con las rutas absolutas queda mas fácil identificar donde están ubicados los archivos al hacer import.
