### ISSUE TITLE
Generar una estrategia para los acordeones que no tengan contenido

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-frontend#403]
## Descripción:

Generar una estrategia a utilizar con los acordeones de las diferentes secciones que no tengan contenido al ingresar por un área de consulta debido a que esta combinación no se hayan calculado.

### Resultado:

Estrategia implementada con el acordeón de Factor de compensación y conectividad.

**Comment by Trjegul84** [comment]
Se abrió el pull-request con la estrategia para los acordeones.  Consiste en pasar el arreglo de componentes a LandscapeAccordion únicamente con los componentes que apliquen de acuerdo  al área de consulta seleccionada. 
Para states y basinSubzones se cargan solo human footprint, forest y connectivity.
Para jurisdicciones ambientales se cargan todas las secciones
Para áreas de manejo especial se cargan solo human footprint y forest.
