### ISSUE TITLE
Error con la interacción de los acordeones de primer y segundo nivel

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#407]
## Descripción:
1. Seleccionar cualquier área de consulta
2. Ir a pestaña paisaje
3. Abrir acordeón de Huella Humana (1er nivel). Por defecto se abre el acordeón de segundo nivel "ACTUAL" y se carga el mapa correspondiente.
4. Cerrar acordeón de segundo nivel "ACTUAL"
5. Cerrar acordeón de primer nivel "HUELLA HUMANA"
6. Abrir acordeón de primer nivel "HUELLA HUMANA". En este caso se abre el acordeón de segundo nivel "ACTUAL" pero el mapa no se carga. De hecho, en este caso, al realizar este paso 6 el acordeón de segundo nivel "ACTUAL" no debería abrirse si no que debería conservar el último estado (cerrado). Ver comportamiento en producción si se quiere mas detalle.

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/25c1c496-d9d4-4a1e-b365-c5dd42fce84c)

@Trjegul84 Sabes si de pronto este comportamiento se vio alterado con el último cambio que se subió para ocultar el acordeón de la sección de "Pérdida y persistencia" de bosques?

### Resultado:
Bug solucionado

**Comment by Trjegul84** [comment]
Se realizaron revisiones sobre el comportamiento de los acordeones en los commits anteriores, obteniendo las siguientes observaciones:

- Enero 7 commit bf74a449: el comportamiento de los acordeones es el esperado, se conserva el estado cuando se colapsan los del primer nivel.

- Enero 25 commit e84ce12a: el comportamiento es igual que el actual. 

- Febrero 2 commit  33d1f1d (actualización de materialUI): el comportamiento es igual que el actual, se expanden los de segundo nivel aunque previamente se hayan cerrado los de primer nivel. 

No se arregla este error. En reunión con el equipo se concluye que el comportamiento es inherente a la migración de los componentes para que funcionen con la nueva versión de material.

**Comment by Trjegul84** [comment]
Se mostró a Cesar el comportamiento de las pestañas y se consultó sobre la necesidad de restablecerlo como estaba antes de la migración del componente y respondió que no es preocupante y que no es urgente, lo que le interesa es que se muestre alguna información cuando el usuario navega en las pestañas. Propone discutirlo en la siguiente planeación de sprint.
