### ISSUE TITLE
Spike: Raster en Biotablero

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#444]
## Descripción: 
Revisar como mostrar raster en leaflet para ser desplegados en Biotablero: 

- [ ] Analizar cómo esta implementación afecta los componentes actuales que gestionan el mapa (Search y MapViewer principalmente). Escribir los resultados como comentarios en esta tarea o como un documento en el drive. 
- [x] Hacer una prueba cargando un raster de prueba y mostrarlo en el mapa de Biotablero

### Resultado:
Análisis de implementación y prueba de carga en el mapa de biotablero

## Consideraciones:
**Tener en cuenta que se van a manejar los dos tipos de capas de forma simultanea.**
Tener en cuenta cómo se van a manejar las URL como parámetro para poder pasarla a través del componente Search
Tener disponible cargar imágenes ráster para mostrar capas que no tendrán interacción (según sugerencia de Jaime)
¿Cómo se podría almacenar mejor? Los raster en memoria, URL para consultar, imágenes en el servidor de BioTablero o en un servidor Geoserver. ¿otras opciones?

**Comment by alegnaaived** [comment]
Enlaces revisados:
https://mappinggis.com/2018/01/accediendo-a-los-datos-de-un-servicio-wms-con-leaflet/
https://leafletjs.com/examples/wms/wms.html

**Comment by alegnaaived** [comment]
Edité las consideraciones para incluir los comentarios del Daily:

Consideraciones:
Tener en cuenta que se van a manejar los dos tipos de capas de forma simultanea.
Tener en cuenta cómo se van a manejar las URL como parámetro para poder pasarla a través del componente Search
Tener disponible cargar imágenes ráster para mostrar capas que no tendrán interacción (según sugerencia de Jaime)
¿Cómo se podría almacenar mejor? Los raster en memoria, URL para consultar, imágenes en el servidor de BioTablero o en un servidor Geoserver. ¿otras opciones?

**Comment by alegnaaived** [comment]
A futuro: ¿Se podría probar con cargar las capas de ecosistemas estratégicos como ráster en lugar de GeoJSON?

**Comment by alegnaaived** [comment]
Se probó mostrando dos raster desde el Geoserver de BioTablero. Se debe manejar con z-index qué raster debe ir encima, manejando los estilos de cada imagen. Las URL del WMS se pueden pasar como props a MapViewer desde Search.
![image](https://user-images.githubusercontent.com/15584917/116618857-41df0e80-a905-11eb-8e79-e1f241bf11eb.png)
![image](https://user-images.githubusercontent.com/15584917/116619263-d5b0da80-a905-11eb-9266-dfdf837ede1a.png)

**Comment by cazapatamar** [comment]
Se realizó una revisión para pasar el raster a postgis y tratar de extraer las geometrías desde allí. Si bien se pudo generar la consulta esta se demoró mucho en generar para un raster muy pequeño, además no se encontró mucho sentido hacer esto para raster de tipo continuo según lo conversado con Jaime.
