### ISSUE TITLE
Bug en el gráfico de integridad - Rio Bogotá

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#448]
## Descripción:
Al consultar el gráfico de integridad de bosques con la subzona hidrográfica 2120 (Rio Bogotá) no carga la capa y no carga el gráfico mostrando un mensaje de "Cargando". En la consola del navegador aparece un error 500 para ambos endpoints. En el despliegue de prueba y en el ambiente local se presenta el mismo comportamiento.

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/3dea0525-8f59-4f0f-b76f-ea249df6b88c)

Los endpoints aparentemente están retornando la información correctamente

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/541a0d6a-78a1-4a4e-976a-7af5dc7025b1)

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/40e1530f-0857-4789-a30a-a0c2d597601a)

### Resultado:
Bug solucionado

### Endpoints relacionados con esta tarea:
/sci/hf/layer?areaType=basinSubzones&areaId=2120
/sci/hf?areaType=basinSubzones&areaId=2120

**Comment by alegnaaived** [comment]
El error ocurre también con otras consultas de subzonas hidrográficas:
![image](https://user-images.githubusercontent.com/15584917/117018370-0bfda980-acba-11eb-8f52-b209ac097bb7.png)

![image](https://user-images.githubusercontent.com/15584917/117018454-2041a680-acba-11eb-8837-3d9cd5766763.png)

**Comment by alegnaaived** [comment]
Al consultar la URL que regresa en el endpoint de áreas de recreación, se identificó que las URL son diferentes:
![Captura de pantalla de 2021-05-04 09-26-18](https://user-images.githubusercontent.com/15584917/117019340-f046d300-acba-11eb-85ab-10e31fd5f8f6.png)

URL que funciona: http://localhost:8080/sci/hf?areaType=pa&areaId=Areas%20de%20Recreacion
URL que NO funciona: http://localhost:8080/sci/hf**/layer**?areaType=basinSubzones&areaId=2120

**Comment by alegnaaived** [comment]
Se probó con el puerto 8080 (a través del gateway) y directamente hacia el back, pero no se obtuvo la misma respuesta documentada. Se sospecha que hay diferentes contenidos de bases de datos.
![image](https://user-images.githubusercontent.com/15584917/117045352-05306000-acd5-11eb-849c-8e3a9cec426f.png)
![image](https://user-images.githubusercontent.com/15584917/117045473-2b560000-acd5-11eb-80c0-0a554cfb81a2.png)

**Comment by alegnaaived** [comment]
![image](https://user-images.githubusercontent.com/15584917/117051162-d8cc1200-acdb-11eb-9e14-730a89c222c8.png)
![image](https://user-images.githubusercontent.com/15584917/117051645-6576d000-acdc-11eb-8124-f7d1989a2dc2.png)
Missing "s" in cases
