### ISSUE TITLE
Crear las gráficas para sección de Diversidad Funcional - Bosque seco

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/biotablero-frontend#456]
## Descripción:

Implementar las gráficas de la sección de diversidad funcional. Estas se pueden consultar en el documento de [visualización](https://docs.google.com/document/d/1KK2WAq8W4v82phdbsqOm91gdPwfDK-HBRXHBXEfru9g/edit#) en el cual César hará un mock up y una descripción de esa sección. En resumen las gráficas son:

- 3 Cifras
- 4 bullets (o barras)

### Resultado:

Gráficas creadas en el acordeón de diversidad funcional

Sección: Plantas del bosque seco

## Consideraciones:
Hay un tercer gráfico, pero es muy complejo y muy específico para este caso. En otras tareas se pueden revisar alternativas para presentarle a Roy. Por ahora pueden ser [ScatterPlot](https://nivo.rocks/scatterplot/) o en últimas un [Radar](https://nivo.rocks/radar/).

**Comment by cazapatamar** [comment]
Dado que aún no está claro cómo va a quedar esta sección, en este sprint sólo se avanzó en revisar el componente de radar y hacer una primera implementación pero con los mismos datos y aspectos de visualización del ejemplo de nivo
