### ISSUE TITLE
Implementación base de la descarga de datos de gráficos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#469]
## Descripción:

Implementar en una gráfica sencilla la descarga de los datos correspondientes.

La idea es que quede la dependencia y el componente reutilizable listo para las otras tareas

### Resultado:
Botón de descarga funcional en una gráfica

## Consideraciones:

- Probablemente sea mejor crear un componente aparte para el botón donde se definan los estilos del mismo, para que pueda ser reutilizado desde todas las gráficas.
- Si es posible discutir con Cesar los estilos de este botón, pero si se demora es mejor hacer 2 PR para no bloquear las demás tareas
- Tomar la gráfica más sencilla para hacer la implementación, podría ser la de factor de compensación (sólo 1).

**Comment by Trjegul84** [comment]
Se crea el nuevo componente funcional para el botón de descarga de datos. 
Queda pendiente la estandarización del nombre del archivo csv que descarga el usuario por cada gráfica.

**Comment by Trjegul84** [comment]
Se acuerda el siguiente nombre estandarizado para los archivos:

bt_nombreseccion_areaId_geofenceId.csv
