### ISSUE TITLE
Problemas en los tooltips de las gráficas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#482]
## Descripción:
Los tooltips de las gráficas (especialmente las de las barras) que se "salen" a la izquierda, quedan por debajo del mapa.

### Resultado:
El tooltip se ve completo

## Consideraciones:
Este problema ya se presentó con dpc en connectividad y se resolvió fijando el ancho del tooltip y dejando que se extendiera verticalmente.

**Comment by cazapatamar** [comment]
Se arreglaron los tooltips de las gráficas de barras (barra delgada, barra grande y multiples barras delgadas) para que tengan una posición absoluta y de esta forma no quedan debajo del mapa cuando son labels muy largos
