### ISSUE TITLE
Spike: Carga de un raster desde geoserver y delinear área de consulta - Geometría de sección de riqueza

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#485]
## Descripción:
Carga de un raster desde geoserver con la capa nacional y delinear área de consulta con el endpoint ya existente (en vector).

Cargar el raster a geoserver, aplicarle los estilos adecuados y configurar la petición en el front (que no queden params quemados) y que se muestran el raster nacional con la geocerca encima.

### Resultado:
Prueba de concepto y determinar comportamiento y complejidad

## Consideraciones:
Configurar estilos y demás configuraciones en geoserver

**Comment by alegnaaived** [comment]
Rama con este spike: https://github.com/PEM-Humboldt/biotablero-frontend/tree/feature/customRaster
![image](https://user-images.githubusercontent.com/15584917/120864931-acade600-c552-11eb-9dad-4dcb9ed46ba1.png)
