### ISSUE TITLE
Agregar leyenda de mapa de calor (con Spike)

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#491]
## Descripción:
Se desea que cuando se muestra un mapa de calor (como es el caso de *Número de especies*), en el mapa, junto al nombre del mapa se muestre una leyenda como la descrita en el [documento de visualización](https://docs.google.com/document/d/1o8oMgIlvkx75c9IGf5R_OSqs6fuA2aDcukY_oFtLMSA/edit#bookmark=id.b7egl4wo2ff7)

### Resultado:

Al cargar el mapa de *Número de especies* se muestra la leyenda del mapa de calor

## Consideraciones:

- Puede que requiera una pequeña investigación para determinar si es mejor armar la leyenda en código o poner una imagen.
- Revisar tema de gradientes en [NIVO](https://nivo.rocks/guides/gradients/)

**Comment by erikasv** [comment]
Se realizó una implementación con css, porque el gradiente de nivo sólo funciona verticalmente.

Se encuentra en la rama [feature/gradientLegend](https://github.com/PEM-Humboldt/biotablero-frontend/compare/feature/spikeRasterDB...feature/gradientLegend) que sale de `feature/spikeRasterDB`. Por esto mismo no se crea PR hasta no decidir la estrategia para cargar el mapa raster.

**Comment by erikasv** [comment]
Se creó la rama [feature/gradientLegend2](https://github.com/PEM-Humboldt/biotablero-frontend/compare/feature/spikeRasterNOS...feature/gradientLegend2) con los mismos cambios pero desde la rama con la implementación de la capa en geoserver para que pueda ser probada

**Comment by cazapatamar** [comment]
Se ve muy chevere! Veo bastante bien la implementación usando CSS y styled-components.

**Comment by erikasv** [comment]
@cazapatamar @Trjegul84 @alegnaaived creé el PR a la rama del `feature/spikeRasterDB` ya que decidimos irnos con esa implementación. Sin embargo no creé ningún PR a develop porque hay que limpiar las cosas de geoserver que alcanzaron a quedar en la rama del spike.

Eliminé la rama `feature/gradientLegend2`, pero me gustaría que conservaramos en el repositorio la de la implementación del geoserver, sólo para referencia si la llegamos a necesitar en el futuro.
