### ISSUE TITLE
Crear paquete para módulo de indicadores

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#519]
## Descripción:

Crear un paquete para hacer el módulo de indicadores independiente del resto de BioTablero.

### Resultado:
Paquete similar al módulo de monitoreo comunitario para el módulo de indicadores

## Consideraciones:
Verificar si es mejor usar Parcel o Webpack para este módulo. Así mismo asegurarse de poder desplegar el módulo individual para poder desarrollar en él sin la demora de CRA en la actualización del servidor de desarrollo.

**Comment by erikasv** [comment]
Al final decidí no crear el PR porque hay mucho código obsoleto ahí y de mezclarlo se va a ir quedando sin usar. Los cambios se pueden ver con la [comparación](https://github.com/PEM-Humboldt/biotablero-frontend/compare/feature/indicatorsPackage)

@alegnaaived puedes continuar con esta rama para la otra tarea para, para no mezclar el ejemplo dummy que pusimos y que no quede el código obsoleto ahí dando vueltas. También favor tener en cuenta que no se van a usar clases en este paquete, sólo componentes funcionales (con hooks)

@cazapatamar resulta que también me tocó cambiar las versiones de eslint y algunos plugins de eslint, entonces mejor usar los mismos del otro paquete, para que quede en la documentación.

**Comment by alegnaaived** [comment]
@erikasv ¿Sabes cómo puedo quitar este error al consultar Indicators.jsx?:
![Captura de pantalla de 2021-09-07 23-01-49](https://user-images.githubusercontent.com/15584917/132444608-cc92f0a3-73cf-455c-9d81-2063ca52b531.png)

**Comment by erikasv** [comment]
Seguro le falta generar el paquete, espera la documentación que Camilo está creando y ahí sí sigue los pasos

**Comment by cazapatamar** [comment]
@erikasv @alegnaaived  Ya quedaron listas las [instrucciones](https://docs.google.com/document/d/18z-zJe8qmCwTLJG904xJvWIzFlG07aUggIRpBtBnVis/edit#) para crear y configurar un nuevo paquete del front

Sientanse libres de ajustar o complementar. También me pueden dejar comentarios en el documento

**Comment by erikasv** [comment]
@cazapatamar @alegnaaived Listo, ya revisé el documento y lo veo bien, le hice algunos pequeños ajustes y agregué la instrucción para ejecutar el paquete en modo dev
