### ISSUE TITLE
Agregar textos explicativos a sección de número de especies

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#522]
## Descripción:
Agregar los textos del botón de información de la sección del número de especies

## Consideraciones:
Actualización 01/10/21:
El lunes (4) o martes (5) Jaime avisará por la sala de BioTablero que los textos están listos para producción.

> Para el 24 de sept Jaime o Cesar nos deben entregar estos textos para alcanzar a integrarlos para el siguiente sprint

**Comment by alegnaaived** [comment]
Esta actividad aún no se realiza porque faltan los textos
