### ISSUE TITLE
Expandir tarjeta de indicadores

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#524]
## Descripción:
Implementar las acciones para los botones `+` y `-` de la tarjeta de de un indiador

### Resultado:
- El botón `+` expande la tarjeta y se ve como está en los mockups
- El botón `-` vuelve a poner la tarjeta en su tamaño reducido

## Consideraciones:
- El botón de descarga queda fuera de este alcance
- Preguntar a Cesar cómo se debe ubicar la tarjeta cuando la que se expande no es la primera (en los mockups sólo se ve expandida la primera) -> Ideal que suba
- Preguntar a Cesar si puede haber más de una tarjeta expandida -> Sólo una

**Comment by alegnaaived** [comment]
Para esta tarea revisé cómo hacerlo y creo que podría ser con estilos, siguiendo este ejemplo:
https://reactjsexample.com/a-react-virtualized-autosizing-masonry-component/
