### ISSUE TITLE
Bug: Cancelar la petición de carga del mapa en la sección de especies

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#554]
## Descripción: 
Cancelar la petición de carga del mapa en la sección de especies, usando el token de cancelación que se implementó con las geometrías de la pestaña de paisaje.

Caso: Se abre la pestaña de riqueza y antes de que cargue el raster, cerrar el acordeón. La petición no se cancela y aunque se cierre la pestaña el mapa igual se muestra.

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/c6959a2c-495d-4d21-b795-cd3011a25e0c)

### Resultado:
Bug corregido

**Comment by erikasv** [comment]
El problema es más complejo de lo que parecía a simple vista, está relacionado con que para cargar el mapa de Número de Especies se hacen 2 peticiones: una para el raster y otra para los valores límite del raster, esta última está bloqueando el flujo de `switchLayer` al ser tratada como una sentencia síncrona (tiene un `await`).

Se realizó un ajuste para resolver las dos promesas al tiempo, pero cuando se cierran los acordeones sólo se cancela la última petición, lo que hace que se cancele la de los límites y se siga cargando el raster.

Se pasa al siguiente sprint para buscar una mejor solución
