### ISSUE TITLE
Verificar cancelación de petición de carga de capa de coberturas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#582]
Cuando se accede a una unidad de consulta y se pasa rápidamente a la pestaña de especies (antes de que cargue la capa de coberturas), después de que termina de cargar la capa de coberturas esta se pone sobre la capa de especies que ya se había mostrado previamente.

# Consideraciones:
El alcance de esta tarea es reproducir y diagnosticar el problema

**Comment by alegnaaived** [comment]
Identifiqué que hay dos peticiones que se quedan en "pending" cuando ya se carga la capa de especies: "se" y "layer":

En esta imagen se muestra las peticiones en estado "pending":

![Captura de pantalla de 2022-02-04 08-34-48.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/2c18834f-325f-42c3-90dc-a7e13020e6e2)

Y en esta imagen se sobrepone el resultado de las peticiones:

![Captura de pantalla de 2022-02-04 08-37-28.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/1d1dd440-ca9b-445a-b604-ebb51a83905d)

**Comment by erikasv** [comment]
Lograste reproducirlo, pero cuál es el diagnóstico?

**Comment by cazapatamar** [comment]
@alegnaaived Puedes revisar el código de switchLayer y métodos que manejan el cambio de capas en el componente del acordeón para ver que puede estar haciendo que no se cancelen las peticiones correctamente. 

El alcance de esta tarea incluye hacer el diagnostico a nivel técnico de tal manera que el otro sprint lo podamos corregir. Según lo que vimos en la presentacipon de Jaime esta semana y lo que hablamos por el chat ya lo habiamos logrado reproducir.

**Comment by alegnaaived** [comment]
El comportamiento de la pestaña de Ecosistemas estratégicos (StrategicEcosystems) es diferente a las otras pestañas (Landscape y Species), 
en el componente Drawer.jsx. Pienso que podemos ajustar ese comportamiento para que también reciba handlerSwitchLayer y ajustar en el componente TabContainer para que reciba una acción de qué pestaña por defecto debe ser seleccionada al ser creado.

Esto lo verifiqué cambiando el valor de la línea 39 del componente Drawer.jsx, y esta línea es la que forza que se llame de nuevo la capa "coverage".

**Comment by erikasv** [comment]
Hay dos problemas:
- El de los acordeones de la pestaña paisaje ocurre porque con la última actualización para cancelar peticiones, sólo se están cancelando las peticiones cuando se cierran todos los acordeones (ya sea de primer o de segundo nivel).
- El de la pestaña especies ocurre porque el cambio de pestaña no genera la cancelación de las peticiones (sumado al comportamiento del punto anterior)

Revisé los llamados a `switchLayer` de las secciones (sin tener en cuenta las interacciones con los gráficos) y creo que podemos simplificar mucho toda la lógica, se me ocurre lo siguiente:
1. Eliminar los llamados a `handlerSwitchLayer` de las funciones `handlerAccordionGeometry` de `Landscape` y `Species` (también tendría que cambiar de nombre), inicialmente esta lógica estaba aquí porque teníamos una versión vieja del Acordeón de Material que no permitía destruir el contenido de los acordeones cuando no estuvieran visibles, pero ahora cada vez que un acordeón se pone visible se monta, entonces se podría dejar el llamado a mostrar la capa cuando se carga la sección correspondiente.
1. Apagar todas las capas y cancelar todas las peticiones cuando se da click en una pestaña (la pestaña también se monta cuando se pone visible, entonces se podrían hacer estos llamados en el `componentDidMount`)

Adicionalmente creo que `switchLayer` necesita un refactor (sí, otra vez 😐), el objetivo principal es que sea más fácil hacerle seguimiento y depurar, por ejemplo los llamados con el callback (como el de [`speciesRecordGaps`](https://github.com/PEM-Humboldt/biotablero-frontend/blob/develop/src/pages/Search.jsx#L688)) son muy complejos de seguir y me parece que la función termina hasta 3 veces en lugar de 2 🤷‍♀️, para esto propongo (pero son sólo ideas que tengo, al momento de implementar puede complicarse el asunto):
1. Crear una función que se encargue de cargar las geometrías al estado (así cuando recién se selecciona el área de consulta cargamos la geometría de la geocerca y ya está disponible para las secciones que la necesitan, como integridad y los rasters)
1. Crear una función que se encargue de cargar los raster, a diferencia de los geojson estos no se pueden almacenar en el estado, entonces siempre que se necesiten toca hacer la petición
1. SwitchLayer se debería encargar sólo de prender y apagar las capas necesarias, pero contando con que las que sean geojson ya estén cargadas en el estado.

**El reto** consiste en lograr manejar los llamados asíncronos cuando las capas aún no están en el estado o las leyendas de los mapas para los raster (esto es lo que no he pensado muy bien aún).

**Comment by cazapatamar** [comment]
@erikasv Estoy de acuerdo con los 2 primeros puntos que planteas: dejar de llamar `handlerSwitchLayer` desde los acordeones y ahora hacerlo desde cada componente correspondiente, y con cancelar las peticiones al cambiar de pestaña. Considero que esos 2 puntos, y de acuerdo a tu diagnostico, solucionarian la mayoria de los bugs (o todos) que tenemos actualmente con el manejo de las capas en producción.

Por otro lado, tambien considero que debemos hacer un refactor grande sobre `switchLayer`. Agregaría a lo que planteas: este refactor quizá deba ser abordado posterior a la actualización de datos, ya que si todo sale bien entonces es probable que dejemos de usar capas vectoriales dando paso a los raster. Mi inquetud es si ahora es el mejor momento para hacer este refactor que es grande y complejo o si mejor esperamos a que se haga la actualización de los datos los cual nos permite tener un panorama mas claro de como queda finalmente los datos geográficos en biotablero.

**Comment by erikasv** [comment]
@cazapatamar Lo que me preocupa de posponer el refactor es que puedan aparecer nuevos bugs, pero tienes razón en que el cambio de tipo en las capas igual nos pueden llevar a un refactor en otro sentido.

Podemos mirar si lo abordamos paulatinamente con el cambio de cada sección a raster, pero por ahora la siguiente tarea se enfocará en lo que mencionas en el primer párrafo.
