### ISSUE TITLE
Diagnosticar actualización de dependencias

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#586]
## Descripción:
Revisar las dependencias y determinar la viabilidad y estrategia par actualizarlas

## Resultado:
Tarea con las instrucciones especiales (en caso de que se requiera) para actualizar las dependencias. Si no se requieren instrucciones especiales, sólo para separar el espacio.

## Consideraciones:
- Es posible que por tema de vulnerabilidades no se requiera actualizar Material, pero es algo que deseamos, así que revisar los pasos para este paquete también.
- Revisar también si se puede actualizar la versión de nivo y si requeriría algunos pasos especiales

**Comment by alegnaaived** [comment]
Usar [yarn audit](https://classic.yarnpkg.com/en/docs/cli/audit/)

**Comment by cazapatamar** [comment]
1. Se analizan dependencias directas del frontend usando el comando `yarn npm audit` el cual arroja que `axios` debe ser actualizada a la version 0.21.2.

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/b3fff124-eef2-4cad-becf-cee652063b5e)

Se hace una prueba modificando en el `package.json` la versión de `axios: ^0.21.1` y luego ejecutando `yarn up` y funciona quitando la alerta de esta dependencia específica. Por ahora no se va a generar un PR con este ajuste mientras no se identifique a nivel general cual es la mejor forma de realizar esta gestionar y actualizar las dependencias.

2. Se analizan dependencias indirectas del frontend usando el comando `yarn npm audit --recursive` el cual arroja que hay 23 dependencias que tienen vulnerabilidades (Severidad: 2-Críticas 8-Altas 13-Moderadas). De estas, se analiza que la mayoria están relacionadas con una dependencia directa `react-scripts` por lo cual se creará una nueva tarea dado que hay que pasar a la versión 5 por lo que se asume que se requiere trabajar en actualizar esta dependencia de manera independiente.

**Comment by cazapatamar** [comment]
Se crearán 3 tareas adicionales:

1. Analizar de manera general cual es la mejor estrategia para actualizar y gestionar las dependencias dentro del front. Profundizar y leer acerca del uso de `^` y `~` para el versionamiento, `yarn install`, `yarn up` y demas comandos que se consideren útiles. Esta tarea busca responder a la pregunta si esta gestion de dependencias es mejor hacerla manual y con un versionamiento fijo o si hay algún proceso mas dinámico.

2. Analizar el proceso de migración de `Material UI` a la versión 5.

3. Analizar el proceso de migración de `react-scripts` a la versión 5.

Despues de culminadas las tareas 1 y 3, se deberían haber solucionado la mayoria de alertas de vulnerabilidad (y las mas críticas) de las dependenicas del frontend.
