### ISSUE TITLE
Realizar análisis para la gestión de dependencias

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#589]
## Descripción:
Analizar de manera general cual es la mejor estrategia para actualizar y gestionar las dependencias dentro del front y back. Profundizar y leer acerca del uso de ^ y ~ para el versionamiento, yarn install, yarn up y demas comandos que se consideren útiles. Esta tarea busca responder a la pregunta si esta gestion de dependencias es mejor hacerla manual y con un versionamiento fijo o si hay algún proceso mas dinámico.

### Resultado:
Estrategia para la gestión de dependencias documentada en un archivo aparte en en google drive

## Consideraciones:
- Tener en cuenta los workspaces de Yarn
- Resultado de la tarea #586

## Revisiones
 - [x] Erika
 - [x] Angela Devia
 - [x] Camilo
 - [x] Angela Checa

**Comment by erikasv** [comment]
Encontré muchas publicaciones con buenas prácticas en otros aspectos, pero parece que el manejo de las versiones de las dependencias no es un tema con tanta preocupación en general 😅

[Este artículo](https://developer.ibm.com/tutorials/learn-nodejs-manage-packages-in-your-project) me pareció muy útil para entender todo el tema del `package.json` y en la sección [automatic-upgrades](https://developer.ibm.com/tutorials/learn-nodejs-manage-packages-in-your-project/#automatic-upgrades) está bien explicado el carret (`^`) y la tilde (`~`). Sin embargo esto aplica para la primera vez que se instala, para cuando no se tiene un lock y al funcionamiento de `npm install`, yarn es un cuento completamente aparte y especialmente la versión `berry`, que es la que nosotros usamos.

La versión que tenemos tanto en el front como en el back es la 2.4.0, la versión más reciente es la 3.1.1, la cual corresponde a la documentación en la [página de yarn](https://yarnpkg.com/cli), por eso es que tantos comandos no funcionan. En el backend hice el ejercicio de actualizar la versión de yarn y entender un poco más como funcionan los comandos y esto es lo que encontré:

- Ya que existe un lock (`yarn.lock`), siempre se instalará la versión que esté ahí. Es por esto que aunque la versión de `node-fetch` esté especificada como `^2.6.1` y ya exista la `2.6.7`, cuando corremos `yarn install` en nuestras máquinas se instala la `2.6.1` porque es la versión que quedó fijada en el lock.
- La versión 1 de yarn tenía el comando `yarn upgrade` que [actualizaba las dependencias](https://robertcooper.me/post/how-yarn-lock-files-work-and-upgrading-dependencies#how-to-upgrade-dependencies) dentro de los rangos especificados en el `package.json`. Sin embargo, en yarn berry no hay un comando equivalente, `yarn up` tiene diferentes opciones para actualizar los paquetes con algunas restricciones, pero siempre los llevará a la versión más reciente sin respetar los rangos especificados en el `package.json`
- El comando `yarn upgrade-interactive` permite escoger la versión a la cual actualizar las dependencias, puede ser a la versión más alta respetando el rango especificado en el `package.json` o la última versión disponible de la dependencia, pero una vez aplicado el cambio también actualizará el `package.json`, así que sólo le veo ventaja a tener el carret o la tilde para saber si hay parches o nuevas versiones menores.

He subido la rama [`feature/updates`](https://github.com/PEM-Humboldt/biotablero-backend/compare/feature/updates) en el backend, en la cual actualizo la versión de yarn, habilito el plugin `interactive-tools` y actualizo la dependencia `node-fetch`. Pueden ejecutar sobre esa rama el comando `yarn upgrade-interactive` para que vean como se muestran las opciones de actualización y como se aplican las mismas (recuerden ejecutar `yarn install` cuando se cambien de rama para actualizar el node_modules).

### Adicionalmente resulta importante actualizar node, la versión que estamos usando actualmente (14) está en mantenimiento hasta abril del próximo año, pero la versión activa es la [16](https://nodejs.org/en/about/releases/). Yarn ahora se [instala](https://yarnpkg.com/getting-started/install) con un paquete disponible desde esta versión de node y tal vez algunas de las nuevas versiones de las dependencias que queramos adoptar también estén usando la versión activa como mínimo (por ejemplo, la última actualización de knex que hicimos nos obligó a actualizar node)

**Comment by cazapatamar** [comment]
De la misma manera que Erika, no encontré algo puntual que responda a las inquetudes que tenemos acerca de como gestionar correctamente las dependencias. De lo que si hay mucha información de lo que es el versionamiento semantico y el uso del gorrito `^` y la tilde `~`, lo cual ya es claro para mi que significa cada uno.

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/be83127d-873e-40bf-8d62-118799d3ea6f)

Sólo encontré este [vídeo](https://www.youtube.com/watch?v=dforsUYxHVE) donde se dice al final que el prefiere no usarlos y tener un versionamiento fijo ya que no se tiene la certeza de si los que desarrollaron todas nuestras dependencias sean estrictos con SenVer. Es decir, se puede dar en caso que se suba un cambio de una `major versión` como una `minor version`. Este es solo uno de los puntos de vista que debemos tener en cuenta, el cual es bastante conservador.

Otro enfoque puede ser usar sólo la tilde `~` para únicamente actualizar los parches y descartar cambios ya sean minor o major. Finalmente, el último enfoque que veo es el menos conservador y es usar el gorrito `^` como lo hemos venido haciendo en algunos de nuestras dependencias hasta ahora y únicamente descartar los `major versions`. Se podría llegar a un punto en el que combinemos los 3 enfoques haciendo un analisis por cada dependencia.

En cuanto a los comandos de `yarn`, estuve revisando la rama que subió Erika, especialmente el comando `yarn upgrade-interactive` ya que lo encontré bastante últil en los recursos que leí acerca de las herramientas para facilitar el actualizar estas versiones. Aunque esté tipo de comandos no responden a nuestra pregunta base si permiten analizar y diagnosticar el estado actual de las dependencias en un momento dado y tomar acciones. Lo que no me queda tan claro es las implicaciones y dificultad de subir la versión de yarn a las 3 y poder usar estos comandos.

Comparto algunos links de los que revisé:

- [Video](https://www.youtube.com/watch?v=dforsUYxHVE)
- Documentacion oficial [semver](https://semver.org/lang/es/)
- [Calculadora semver (Erika ya lo había compartido)](https://semver.npmjs.com/)
- [semver y actualización de dependencias en npm](https://lenguajejs.com/npm/administracion/actualizar-dependencias-npm/)
- [How to efficiently update your npm dependencies?](https://code-trotter.com/web/how-to-efficiently-update-your-npm-dependencies/#using-yarn)
- [yarn upgrade-interactive](https://yarnpkg.com/cli/upgrade-interactive)

**Comment by Trjegul84** [comment]
He revisado los videos y recursos mencionados.  También considero que no deberíamos seguir usando el ` ^`  pero no tengo claridad si hay algunos casos que nos puedan servir. Tratando de buscar algo que complemente esta tarea encontré las siguientes herramientas que ayudan a actualizar automáticamente y encontrar vulnerabilidades en las dependencias:
[Dependabot](https://github.com/dependabot/dependabot-core) y este [Video de dependabot](https://youtu.be/TnBEVPUsuAw)

[Snyk antes Greenkeeper](https://snyk.io/)  *creo que es de pago 

También encontré [Travis-ci](https://www.travis-ci.com) para realizar pruebas automáticas pero no estoy de forma ayuda al manejo de dependencias. 

Lo que veo que recomiendan para realizar casos como el nuestro es utilizar herramientas de automatización como comprobadores de dependencias y CI para automatizar y optimizar el proceso. Sería ideal poder contar con una herramienta que nos ayude a realizar esta depuración de forma más precisa, continua y automática. Por ejemplo, con **Dependabot** los PR se crearían de forma automática en el repositorio.

**Comment by erikasv** [comment]
Para que tengan en cuenta:

El enlace que compartió @cazapatamar  *"How to efficiently update your npm dependencies?"* cuando hablan del `upgrade-interactive` corresponde a una versión más vieja del comando, ahora ya incluye las últimas versiones en su forma por defecto, pero todavía permite diferenciar las que están en el rango definido en el package.json

Con respecto a lo que menciona @Trjegul84, no sé en qué momento se habían desactivado las alertas de seguridad, ya las volví a habilitar y ya las pueden ver en los repositorios, pero no estoy de acuerdo con habilitar los PR automáticos porque precisamente no tenemos pruebas. Y sobre la sugerencia de travis-ci, de nuevo, no tenemos pruebas y además no tenemos nada tan avanzado que no se pueda hacer con los actions de github ([aquí una comparación por encima de ambos servicios](https://knapsackpro.com/ci_comparisons/github-actions/vs/travis-ci)).

**Comment by alegnaaived** [comment]
En este [enlace](https://dev.to/th0rgall/the-basics-of-dependency-maintenance-in-npm-yarn-4c1l) recomiendan revisar dependencias por actualizar cada 2 o 3 meses.

Como no entendía lo del versionamiento semántico, lo revisé en este [enlace](https://www.baeldung.com/cs/semantic-versioning).

Comparto algunos de los enlaces que comencé a buscar:

https://yarnpkg.com/cli/up
https://www.npmjs.com/package/upgrade-yarn-workspaces-deps
https://egghead.io/lessons/yarn-use-yarn-up-to-update-dependencies-in-a-yarn-workspace
https://stackoverflow.com/questions/56681766/upgrading-yarn-in-root-directory-do-not-upgrade-workspace-dependencies

**Comment by alegnaaived** [comment]
Erika mencionó "immutable" como una opción durante la reunión. Encontré este [ejemplo](https://yarnpkg.com/cli/install#examples).

**Comment by erikasv** [comment]
- Acordamos una [política de dependencias](https://docs.google.com/document/d/1TGc0AX6aIhxKNArgszvij6KRoHZ0uYSzuTMfRvDDO-E/edit#heading=h.e8zmbgig5zsl)
- Se creó una tarea para las actualizaciones de cada repositorio, teniendo en cuenta que ya existen dos tareas independientes para las librerías grandes del front
- Acordamos que la próxima vez que haya que instalar una nueva dependencia se debe hacer con `yarn add -T <paquete> [-D]` y en caso de que no funcione tratar de identificar el inconveniente antes de agregar más pasos a esta nueva "rutina"
