### ISSUE TITLE
[Spike] Multiples gráficas en plotly

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#591]
# Descripción
Para las gráficas del módulo de monitoreo comunitario se desean tener algunos gráficos que técnicamente corresponden a dos gráficos en uno, por ejemplo un gráfico de áreas y un gráfico de líneas, pero no sabemos si se puede realizar.

Los primeros casos en los que necesitamos esto es para los [gráficos de la metodología 6](https://docs.google.com/document/d/1ENy7A495Zzl9ftjCNQUAYQykhVHAJHkvEZKMJGi8x1I/edit#heading=h.fnthgya8dehk)

# Resultado
Pruebas sobre la librería y determinar si es posible.

## Consideraciones
Angela Checha tiene un ejemplo con dos graficas superpuestas, pero sin integrarlo en un proyecto en React. Se propone que esta tarea se enfoque en llevar este ejemplo al módulo de monitoreo comunitario.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/591?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by alegnaaived** [comment]
Comparto los dos enlaces que comencé a revisar:

- https://plotly.com/python/graphing-multiple-chart-types/

- https://stackoverflow.com/questions/62287001/how-to-overlay-two-plots-in-same-figure-in-plotly-create-pareto-chart-in-plotl

**Comment by Trjegul84** [comment]
Se realizó un ejemplo de manejo de multiples gráficas con Plotly.  Se pueden ver en la rama [feature/multigraphsSpike](https://github.com/PEM-Humboldt/biotablero-frontend/tree/feature/multigraphsSpike)
Los ejemplos únicamente funcionan en la pestaña AMUSI y tiene datos "dummy" no se replica el mismo mecanismo de carga de datos que ya se tiene para Monitoreo.

NOTA:
Algo sucede con el footer cuando se agregan varias gráficas en una sección, en ocasiones se observa sobrepuesto sobre la última gráfica.
