### ISSUE TITLE
Actualización de dependencias del frontend

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#598]
De acuerdo a los resultados de la tarea #586 y la decisión tomada en la tarea #589, realizar la actualización de las dependencias del frontend, teniendo en cuenta lo siguiente:

-  Actualizar yarn (`yarn set version berry`)
- Instalar el plugin que habilita `yarn upgrade-interactive` mediante `yarn plugin import plugin-interactive-tools`
- Verificar los cambios que podrían ser necesarios para las versiones mayores y aplicar las que se puedan (ignorando MUI y react-scripts)
- Actualizar parches y versiones menores de las demás

### Consideraciones
Si **es necesario** llevar un paquete a una versión mayor, por ejemplo porque necesitamos un parche que ya no será aplicado a la versión que tenemos o por que va a dejar de recibir mantenimiento en el corto plazo, pero esta actualización resulta muy compleja se debe crear una tarea exclusiva para este paquete.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/598?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Se realizó la actualización de dependencias de forma progresiva a la versión más compatible. Las que no se lograron llevar a la versión _latest_ se actualizaron a la versión _range_. Por cada dependencia se verificó si se presentaban problemas.

Leaflet se deja igual para no afectar los avances que se han realizado en la sección de Dibujar Poligono. Por la misma razón se dejan intactas las siguientes librerias: react-leaflet, react-leaflet-draw y leaflet-draw. 
Cuando se retome la tarea de dibujar polígono se debe verificar si se pueden actualizar las librerías relacionadas.

Las versiones finales después de esta actualización (salida de `yarn upgrade-interactive` al día de hoy) se encuentran en el documento [Versiones Dependencias Biotablero 14-Feb-2022](https://docs.google.com/document/d/178A1xhM7Xt0osXGpCqxGVgXORFseo0fgkCwNPcVJ9wY/edit?usp=sharing).

De este proceso resultaron las siguientes observaciones:

**react-spring:**
Se recomienda intentar actualizar react-spring a la versión ~9.4.3 en la misma tarea de react-scripts y revisar si se puede encontrar una solución para quitar las banderas de build en false del package.json 

**nivo deps**
cuando se intenta actualizar nivo a la versión latest se problema en los tooltips de FC y biomas, Huella Humana Actual y persistencia, Conectividad actual y EE.

**rollup plugin-node-resolve**
Se intento actualizar el plugin sin haber actualizado primero rollup y se presentaron errores al realizar build de los paquetes. La actualización a latest de @rollup/plugin-node-resolve solo fue posible después de actualizar rollup a latest.

**eslint plugins**
Solo se actualizaron dos plugins (eslint-plugin-import y eslint-plugin-jsx-a11y) porque si se actualizan a latest (en rojo) se generan errores al arrancar el front y cuando se ejecuta el comando `run lint`

**eslint-plugin-react**
Al actualizar  eslint-plugin-react  a la versión latest, aunque esta resaltada en amarillo, se presentan 5 errores con propType, deafultProp y prop validation y no arranca el el front.

**parcel**
Se actualizó parcel de indicadores a la versión latest 2.3.1 sin problema.Sin embargo, aún queda pendiente un parcel en la salida del comando upgrade-interactive que corresponde al de cbm-dashboard (Monitoreo), éste se actualizó desde la versión 1.12.3 a range 1.12.4, no se puede actualizar a la ultima versión porque genera errores, para migrar parcel de este paquete a la ultima versión 2.3.1 se debe seguir la [guía de migración](https://parceljs.org/getting-started/migration/).

**plotly.js de monitoreo**
Al cambiar plotly.js desde la versión 1.58.4 a la versión latest 2.9.0 se observa que las gráficas funcionan pero los tooltips de los diagramas de barras y de lineas ya no salen al mismo tiempo, cuando se realiza mouse over solo sale uno. Considerar esto para la [Tarea del front #591](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/pem-humboldt/biotablero-frontend/591) o informar si por significar cambios grandes se debe reversar. 

**react-router-dom**
Solo se logra actualizar react-router-dom a la versión range 5.3.0. Para actualizar a la versión >6 o a latest 6.2.1 se debe seguir la guiá de migración [Upgrading from v.5](https://reactrouter.com/docs/en/v6/upgrading/v5) de lo contrario genera varios errores. 

Nota:
Desde los últimos 5 commits se empezó a presentar un problema de rendimiento en mi ambiente local en el navegador cuando inicio el front, se ralentiza el navegador y solicita detener el script. Por favor revisar si sucede lo mismo en sus ambientes.

**Comment by Trjegul84** [comment]
De las vulnerabilidades previamente analizadas solo se resuelven las siguientes:

1. axios
2. hosted-git-info:
3. node-fetch:
4. safer-eval:
5. serialize-to-js
