### ISSUE TITLE
Actualizar dependencias de Nivo

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/biotablero-frontend#599]
## Descripción:
Se debe actualizar las siguientes dependencias de Nivo a la versión latest
@nivo/bar 
@nivo/bullet
@nivo/core
 @nivo/line
 @nivo/pie 
@nivo/tooltip 

### Resultado:
Dependencias de nivo actualizadas a la versión latest más compatible.
Las gráficas del front no deben estar afectadas.

## Consideraciones:
Revisar todos los tooltips de cada gráfica.

**Comment by Trjegul84** [comment]
Al actualizar las dependencias de nivo a 0.79.0/0.79.1 se presenta un cambio en los tooltips de las graficas de barras. 
![Screenshot_20220210_153301.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/95488b7d-5e6b-4bcc-98a0-77650f2fb441)
El color del fondo del tooltip cambia, entonces las letras blancas se vuelven invisibles al realizar movimientos con el mouse fuera del área de la barra. 
![Screenshot_20220210_153238.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/d414c333-c1d3-43e5-a2d0-2b8fa118fcc3)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/599?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84
