### ISSUE TITLE
Corregir bug al crear nuevo proyecto en módulo de compensaciones

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#609]
## Descripción:
Corregir bug al crear nuevo proyecto en módulo de compensaciones el cual sólo se presenta en el ambiente de producción y que muestra el siguiente error en la consola al hacer clic en el boton para crear nuevo proyecto. Puede estar relacionado con el doble slash `\\` que se ve en el llamado al endpoint.

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/74feea10-667e-4a43-b75f-3e2c6f85c20e)

Esto sale en la pestaña network

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/2d1ac9b6-811d-4dee-a2d2-56da2f0d3022)

En el ambiente local, apuntando a bd de pruebas funciona y esta es la peticion que se hace

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/1573b8aa-3925-4044-b443-cc31fa527f8c)

### Resultado:
Bug corregido

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/609?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by erikasv** [comment]
Era un problema de permisos en la base de datos

**Comment by cazapatamar** [comment]
Revisado en el ambiente de producción y todo parece funcionar bien. No guardé el proyecto para no generar datos basura en la bd pero ya está superado el problema al darle clic en el chulito para crear el proyecto.

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/bc14cdec-eff9-49ed-a71e-016a54da7990)

**Comment by erikasv** [comment]
@cazapatamar aunqeu no hayas guardado los biomas, el proyecto nuevo sí se creó, si puedes porfa borralo de la base de datos, sino me dices y yo lo borro

**Comment by cazapatamar** [comment]
Listo, borrado. En la tabla hay otras pruebas que no parecen se datos reales para que los tengamos en cuenta por si en algún momento hacemos una limpieza de esos datos.

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/d68aafe3-54df-4126-83c1-e4344cc66c73)

**Comment by Trjegul84** [comment]
Listo, borré 20 registros de prueba.  No estoy segura de los gid 165, 201, 203 y 204.
