### ISSUE TITLE
Ajustar colores de coberturas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#634]
# Descripción
Ya que se terminó la implementación de las capas y datos de coberturas, coordinar con César para ajustar los colores de barras y capas.

**Importante:**
Actualizar el [archivo de paleta de colores](https://docs.google.com/spreadsheets/d/1qfrKDOG7Fz0tQjKBS5zuaocZ92RuQJR4r9oajwFqp1Y/edit#gid=0)

# Consideraciones
Aunque los datos de áreas protegidas no se han actualizado, los colores se pueden ajustar de una vez
- Se incluye en esta tarea el ajuste en `develop` del error generado en `changeTab` después de la resolución de conflictos

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/634?planning-poker) with ZenHub @cazapatamar @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Se actualizó el archivo excel de paleta de colores.

**Comment by Trjegul84** [comment]
NOTA:
Revisar el tooltip que sale en las barritas de Ecosistemas, cuando está muy a la derecha el usuario no puede ver el texto.
