### ISSUE TITLE
Realizar prueba de cajas de textos con Cesar

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#638]
# Descripción

En la última planeación quedamos de buscar un espacio con César para intentar ajustar los textos. El objetivo es hacer esta prueba en una sola sección, por ejemplo coberturas, y luego ver si se puede replicar a las demás secciones.

Esta prueba implica crear nuevos botones que muestren y escondan textos, similares a los de la `i`

# Resultado

Prueba en una sección para estimar si se lograría implementar el cambio para el lanzamiento.

# Consideraciones

Se debe coordinar el tiempo con César.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/638?planning-poker) with ZenHub @cazapatamar @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Se trabajó con Cesar en la prueba de implementar una sección de solo botones al final de las graficas en cada acordeón. En esta se ubicarán los textos dividios en tres partes:
*Quote = autoría / citación
*Meta= Metodología
*Cons = Consideraciones
Y la información con información para interpretar la gráfica quedará arriba de la misma y visible a apenas se abra el acordeón.  *Text = información de la gráfica.

Se creó la rama `feature/tryAdjustText` con estos cambios. 
**IMPORTANTE**:
En esta tarea se crearon los estilos necesarios para usar los nuevos botones en todas las secciones.

**PENDIENTE**:
Es necesario revisar lo siguiente:
- Optimizar el código porque hay muchas funcionalidades repetidas
- Revisar si se puede agregar al botón de descarga de CSV el mismo estilo de tooltip que tienen los otros botones creados en esta rama 
- Verificar si los estilos creados aplican para la sección de Especies.
