### ISSUE TITLE
Arreglar carga tardía de capa en especies

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#652]
# Descripción
Como se evidencia en el primer comentario, en algunos casos la capa de especies (número de especies) se queda pegada en el mapa. Esto sucede cuando no se deja terminar de cargar la capa y se cambia de pestaña o se da al botón de atrás.

# Resultado
Si se cambia de vista (otra pestaña o atrás) antes de que cargue la capa de número de especies no se debe mostrar en el mapa.

# Consideraciones
- El problema puede estar relacionado cuando la petición de la capa termina pero el procesamiento de la misma no y efectivamente se procesa después de que se ha dado en el botón de atrás.

**Comment by Trjegul84** [comment]
Después de realizar pruebas en la rama develop se observa que la capa de Especies si se queda "atascada" cuando se cambia de pestaña desde Especies a otra pestaña o cuando se regresa con el back button a la pantalla inicial de Consultas. 
![Screenshot_20220825_155524.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/6e09163d-a2f7-410e-9b62-1d3b2852046b)

![Screenshot_20220825_155232.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/a7b54979-97c2-4336-a114-4905a71669c0)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/652?planning-poker) with Zenhub @cazapatamar @ManuelStardust @Trjegul84
