### ISSUE TITLE
Typescript: Migrar CurrentPAConnectivity

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#683]
## Descripción:

Tomar los resultados de la tarea #682 como base para realizar la migración de este componente.

### Resultado:

Componente migrado a typescript

## Consideraciones:

Se alienta a todo el equipo a hacer preguntas cuando se revise el código, así no se tengan sugerencias o sólo sean dudas.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/683?planning-poker) with ZenHub @cazapatamar @ManuelStardust @Trjegul84
