### ISSUE TITLE
Implementar vista post-ingreso polígono

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#702]
# Descripción
Implementar una primera versión de la vista después de enviar el polígono. Se acuerda lo siguiente:

- Agregar una nota en las instrucciones para dibujar un polígono sobre el tiempo que puede demorar la consulta
- Como nombre de la unidad en el header del sitio poner "Area consultada"
- Dejar las Hectáreas totales (se deberán calcular en alguno de los scripts)
- Se mantendrán todas las pesatañas pero sólo Paisaje estará habilitado

# Consideraciones

- Crear los mockups de datos que sean necesarios para las gráficas
- Los nuevos nuevos archivos deben ser escritos de una vez en typescript
- No se recomienda reutilizar el componente Drawer (por la experiencia con Compensaciones y Consultas)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/702?planning-poker) with ZenHub @cazapatamar @danflop @ManuelStardust @Trjegul84

**Comment by erikasv** [comment]
Al empezar la tarea nos dimos cuenta de que hay que tomar muchas decisiones sobre los componentes existentes ya que tal vez no sea tan buena idea crear otro componente aparte, se desea contar con la opinión de Camilo y por lo tanto se pospone esta tarea uno o dos sprints

**Comment by Trjegul84** [comment]
Se identificó que un posible próximo paso puede ser empezar a migrar poco a poco los componentes del folder `charts` y decidir sobre estrategias para migrar componentes muy grandes como `Search`.

**Comment by erikasv** [comment]
Se decide crear otra tarea para separar mejor el trabajo requerido para esa vista
