### ISSUE TITLE
Arreglar warnings de propiedades de StrategiesBox

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/biotablero-frontend#730]
## Descripción:
Se presentan dos warnings relacionados con los tipos cuando se ingresa al módulo de Compensaciones >>ZONA NORTE>> LICENCIADO >> Cartagena >> Donde cómo. 

> Warning: Failed prop type: The prop ea is marked as required inStrategiesBox, but its value is undefined

> Warning: Failed prop type: The prop subBasinis marked as required inStrategiesBox, but its value is undefined``

Es posible que esto se deba a datos corruptos en la base de datos. Se debe hacer un manejo para que no se muestren componentes incompletos debido a la ausencia de estos dos datos.

### Resultado:
Supresión de los warnings, manteniendo el correcto funcionamiento de proyectos con estrategias guardadas.

## Consideraciones:
Se puede ver el error en el comentario del PR [727](https://github.com/PEM-Humboldt/biotablero-frontend/pull/727)
 - Consultar con Daniel si se debería ocultar la caja de compensaciones guardadas si no hay información de subzona o jurisdicción, o si se debería mostrar un mensar "dummy" en cada campo.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/730?planning-poker) with Zenhub @cazapatamar @ManuelStardust @Trjegul84

**Comment by erikasv** [comment]
Las propiedades sí existen, la única forma de que no existieran es por corrupción de la base de datos, se revisó y el problema fue cuando se hizo la actualización de las tablas de subzonas y jurisdicciones.
