### ISSUE TITLE
Corregir comportamiento de capa transparente al hacer clic en selector de unidad de consulta

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/biotablero-frontend#733]
## Descripción:
Cuando se da clic en el selector de un tipo de área de consulta (Departamentos, Jurisdicciones ambientales o Subzonas hidrográficas) se carga el mapa de Colombia dividido en esas unidades de consulta.

La capa que se carga está descuadrada, al poner el mouse encima se muestra un cuadro negro y al retirar el muse se quita la unidad seleccionada.

### Resultado:
La capa se debe cargar sin estar corrida, al poner el mouse encima se debe mostrar el nombre de la unidad señalada y al retirarlo no se debe borrar.

## Consideraciones:

Se adjuntan pantallazos de ejemplo.

![Screenshot_20220825_200436.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/4422b0ae-937a-462a-8f60-1200bcad115d)
![Screenshot_20220825_155955.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/120bd518-32fa-4e2f-8e1f-f71c088cd473)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/733?planning-poker) with Zenhub @cazapatamar @ManuelStardust @Trjegul84

**Comment by cazapatamar** [comment]
No pude reproducir el desplazamiento de la capa pero encontré otro error. Cuando se pasa el mouse por las diferentes estados/departamentos/subzonas estas se van borrando del mapa y como dice Angela aparece un cuadro negro que debe estar relacionado con el tooltip que seguro se está intentando mostrar pero en este caso no aplica.

Esta imagen es de producción:

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/102e9205-af9b-41fa-907b-3661b1641d0d
)

**Comment by cazapatamar** [comment]
Lo mas seguro es que esté relacionado con el refactor que se hizo sobre el manejo de las capas en el componente Search, especificamente en el metodo highlightShapeFeature o resetShapeHighlight.
