### ISSUE TITLE
[Spike] Entender separación de lógica e interfaz

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#757]

**Comment by Trjegul84** [comment]
Durante la investigación de este tema encontramos estos recursos:

**Separación de la UI y la lógica de negocio**
https://askcodes.net/questions/reactjs-separation-of-ui-and-business-logic
https://docs.react-async.com/guide/separating-view-logic
https://medium.com/swlh/decoupling-logic-from-react-components-f6035646c275

Ejemplos:
https://stackoverflow.com/questions/69332889/reactjs-separation-of-ui-and-business-logic
https://gist.github.com/negamaxi/9e2736e5b58b23f232f33b1430ed556e

**Separation of concern**
https://krasimir.gitbooks.io/react-in-patterns/content/chapter-13/
https://tooltime.tech/react-apps-separation-of-concerns/

**Comment by Trjegul84** [comment]
Durante la investigación de este tema encontramos estos recursos:

**Separación de la UI y la lógica de negocio**
https://askcodes.net/questions/reactjs-separation-of-ui-and-business-logic
https://docs.react-async.com/guide/separating-view-logic
https://medium.com/swlh/decoupling-logic-from-react-components-f6035646c275

Ejemplos:
https://stackoverflow.com/questions/69332889/reactjs-separation-of-ui-and-business-logic
https://gist.github.com/negamaxi/9e2736e5b58b23f232f33b1430ed556e

**Separation of concern**
https://krasimir.gitbooks.io/react-in-patterns/content/chapter-13/
https://tooltime.tech/react-apps-separation-of-concerns/
