### ISSUE TITLE
Cargar capas iniciales

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#775]
# Descripción y Resultado

Cuando se entra a la sección Portafolios por temática, se debe mostrar en el mapa las capas de los portafolios existentes para la primera temática.

# Contexto

El mapa por defecto de esta sección son las capas de los portafolios existentes para la _primera temática_ (por lo regular será Especies).

# Consideraciones
- Trabajar todo lo relacionado con estas capas con la función `setSectionLayers`
- No quemar valores en el componente Targets, se debe trabajar con los resultados del backend.
- En la tarea #774 se realizaron los ajustes en el backend para que CARDER sirva para los siguientes casos:
    - No tiene portafolios para Especies. Tener en cuenta que en este caso la primera temática no será Especies y se deben cargar las capas para la siguiente temática.
    - No tiene el portafolio 3 en la primera temática (de hecho no lo tiene en ninguna), en este caso no se mostrarán 4 capas (la de los mockups) sino sólo 3
- Se debe editar el mockup de las capas para quitar la capa por defecto y retornar un error en caso de que el id de los portafolios no sea un número del 1 al 4 (ver el tipo de error en uno de los otros servicio).

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/775?planning-poker) with Zenhub @danflop @ManuelStardust @Trjegul84

**Comment by cazapatamar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/775?planning-poker) with Zenhub @erikasv
