### ISSUE TITLE
Agegar leyenda a la derecha del gráfico

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#777]
# Descripción y resultado

Agregar la leyenda de la derecha del gráfico, ésta indica cuál es el 100% de la meta y la unidad en la que se mide para cada temática.

Primero debemos intentar poner esto dentro del componente del gráfico para que no dañe la parte responsiva. Si no se logra, intentar si hay una forma de ponerlo por fuera del componente del gráfico, pero sin dañar la parte responsiva.

Si ninguna de estas dos opciones es posible, hablar con Cesar a ver si podemos manejar esa información de otra forma. Si no se puede, la implementación se debe hacer teniendo un gráfico por grupo de barras con su leyenda a la derecha (en este caso se manejan los 2 elementos desde el componente de Targets). En este caso también discutir con Cesar otra forma para indicar la temática seleccionada, algo similar a como se maneja en Número de especies (oscurecer y aclarar los colores de las demás gráficas se vuelve costoso)

# Consideraciones
- Dedicar máximo 1 día a las primeras alternativas.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/777?planning-poker) with Zenhub @danflop @ManuelStardust @Trjegul84 @erikasv

**Comment by erikasv** [comment]
@cazapatamar @Trjegul84 @cazapatamar En la rama [feature/porfoliosTotalsLegend](https://github.com/PEM-Humboldt/biotablero-frontend/tree/feature/porfoliosTotalsLegend) Puse una primera versión con otra opción comentada, quien tome la tarea puede hablar con Cesar para ajustar detalles de visualización.

También sugiero cambiar algunos totales y unidades en los mockups, para ver cómo quedan con distintos valores y longitudes
