### ISSUE TITLE
Interacción leyendas -> mapa

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#779]
# Descripción y resultado

Las leyendas que estén habilitadas deben permitir encender y apagar las capas del portafolio correspondiente.

Adicionalmente tratar de resolver el comentario dejado sobre la propiedad `defaultChecked` de los Checkbox

# Consideraciones

- Esta interacción no debe requerir realizar nuevamente la petición para las capas cuando se vuelven a encender, todo se debe manejar con la transparencia de la capa.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/779?planning-poker) with Zenhub @danflop @erikasv @ManuelStardust @Trjegul84
