### ISSUE TITLE
Ajustes para consulta por ingreso de polígono - Pérdida y persistencia

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#807]
# Descripción
Preparar el front de BioTablero para mostrar los resultados de la consulta por ingreso de polígono.

- Crear un nuevo archivo para manejar las peticiones al backend de biab
- Poner una nueva variable de ambiente para el host del backend de biab
- Transformar el polígono que se tiene desde leaflet draw para que quede en formato wkt
- Asegurarse de que las peticiones get y post funcionen bien

# Consideraciones
- Verificar qué se puede hacer desde leaflet directamente para la extracción del polígono en wkt
- Las peticiones se pueden probar desde search o con datos quemados, no hacer la conexión con el controlador de Pérdida y persistencia

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/807?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by cazapatamar** [comment]
Queda pendiente revisar la transformación a WKT del objeto MULTIPOLYGON

**Comment by cazapatamar** [comment]
Se soluciona el problema enviando parametro epsg_polygon = 4326
