### ISSUE TITLE
Quitar modal del mapa cuando la peticion de dibujar polígono falla

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#831]
# Descripción y resultado

Actualmente si hay un error en la petición al servidor de biab el modal de "cargando" se queda pegado y nunca se quita. Debe quitarse y dejar el polígono dibujado. En la sección de la gráfica ya hay un mensaje que indica que la información no está disponible.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/831?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by ManuelStardust** [comment]
La tarea implica un cambio mayor al inicialmente evaluado, así que se decide cerrar y se crea una nueva tarea para lograr el uso de otras propiedades adicionales relacionadas con el manejo del polígono.
