### ISSUE TITLE
Ajustar el comportamiento del polígono en el mapa

### ISSUE THREAD

**Issue by ManuelStardust** [PEM-Humboldt/biotablero-frontend#833]
Hacer que el poligono quede fondo transparente y con el borde cuando si hay resultados de PP.

# Consideraciones

Cuando no hay datos o error se debe mantener el fondo del poligono como está.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/833?planning-poker) with Zenhub @erikasv @ManuelStardust
