### ISSUE TITLE
Migrar a NIVO el componente DotsGraph.jsx

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#891]
El componente ´DotsGraph.jsx´ (gráfico de puntos que se usa en el módulo de compensaciones) usa la libreria VX la cual se usó para todos los gráficos antes del 2019. Todos los otros tipos de gráficos ahora usan la libreria [NIVO](https://nivo.rocks/). El objetivo de la tarea es evaluar técnicamente si NIVO tiene un gráfico de puntos que ofrezca las misma funcionalidad actual y en tal caso implementarlo para reemplazar el componente actual. Se sugiere:

1. Revisar documentacion de NIVO y familiarizarse con los componentes que ofrece para renderizar gráficos en React.
2. Familiarizarse con el esquema actual en biotablerio de implementacion para los gráficos que actualmente usan NIVO (Todos los del módulo de consultas).
3. Implementar un gráfico de puntos en biotablero, usando NIVO, con datos de prueba y que se sea similar al actual. Por facilidad se puede poner en el mismo componente (al mismo nivel) para poderlos comparar.
4. Migrar el componente actual ´DotsGraph.jsx´ desde VX a NIVO. El nuevo componente debe estar en TypeScript

**Comment by hacheG** [comment]
Se esta haciendo un proyecto de testeo para probar las funcionalidades de la gráfica ScatterPlot de NIVO, por el momento se le están pasando algunos datos dummie y con estos se ha logrado tener las tres variables requeridas, eje X, eje Y y  el diámetro de la circunferencia como eje Z. También se esta trabajando en los estilos del tooltip

**Comment by hacheG** [comment]
se tiene la gráfica dummie con tres colores,con valores en los ejes X, Y y Z con un tooltip en fondo negro, con el tamaño y el color listos para los ejes X y Y, con su responsive, pero aun no se ha implementado en biotablero

**Comment by hacheG** [comment]
la grafica ya acepta los datos del backend, permite que se visualicen diferenciandolos entre alto, medio y bajo con un color. El eje Y tiene los valores pedidos desde el 4 al 10 con paso de 0.5 entre cada entero, sin enbargo NO se a logrado que los valores enteros se muestren como decimales 4.0...10.0.
El tamaño de las circunferencias se logra pero de una manera generalsiendo siempre el valor menor un diametro pequeño y para el valor mayor un diametro grande, sin poder hacer que los tamaños sean particulares a cada grafica.
Por ultimo el eje X que esta seteado en automatico NO permite que se termine en un valor impar

**Comment by hacheG** [comment]
se hizo la migración completa de la gráfica incluyendo el typescript, falta la revisión de temas de diseño por parte de Cesar por esta razón no se hizo el PR, sin embargo la rama se encuentra en el repositorio

**Comment by erikasv** [comment]
Para resolver el problema del identificar el bioma seleccionado tuve que implementar un componente personalizado, porque no encontré otra forma de identificarlo sin apoyarnos en efectos colaterales, los cuales pueden dañar todo en cualquier momento y no darnos cuenta porque Compensaciones no es un módulo que revisemos mucho. Un ejemplo de que las cosas se dañan en nivo entre versiones menores es este: https://github.com/plouc/nivo/issues/1916. Precisamente de ahí saqué lo de hacer un componente personalizado (aunque ya lo habíamos hecho para el Bullet).

Esto desconecta el tooltip y toca reimplementarlo, tal cual como se hizo con el Bullet, entonces queda pendiente eso de esta tarea

**Comment by hacheG** [comment]
para implementar el tooltip se ajusto el componente personalizado (getComponent) basado en el codigo de git del creador y en los tipos que este tenia
