### ISSUE TITLE
Revisar y arreglar bug compensaciones

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#894]

**Comment by hacheG** [comment]
La aplicacion se cae al intentar igresar al modulo de compensaciones desde el local, deberia verse como en produccion:
<img width="1345" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTZHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6f7c2caf9bb73d316183f98127eda3dc5eea465/image.png" alt="image.png" />
sin embargo el error que muestra es:

**Comment by hacheG** [comment]
Se han hecho varias pruebas comentando dos partes del codigo, en Compesation se comento el componentWillUnmount lo cual hace que no se caiga la aplicacion pero no ingrese a ver el mapa, ni los datos; Por otro lado en App se comenta el setHeaderNames (como componente funcional) y la aplicacion funciona, sin embargo el heder que idica al usuario el departamento y la zona que esta visualizando no se muestra. Se cree que este asunto se podria arreglar usando de manera correcta el setHeaderNames en un useEffect

**Comment by ManuelStardust** [comment]
Se realizo la prueba de incluir setHeaderNames en un useEffect, sin embargo el error continua, también se probo renombrando la función y comparando con el estado previo de headerNames, pero tampoco arrojo un resultado diferente.

**Comment by ManuelStardust** [comment]
Se lograron solucionar los errores relacionados con componentWillUnmount y componentDidUpdate sin embargo se pide aydua para revisar dado que puedee surgir otro errores. Se deja cargado para pruebas en la rama: [https://github.com/PEM-Humboldt/biotablero-frontend/tree/feature/compensationBug](https://github.com/PEM-Humboldt/biotablero-frontend/tree/feature/compensationBug)

**Comment by erikasv** [comment]
Tal como explicó Manuel, el bug no es exclusivo de compensaciones.  Al probar en `develop`, en el módulo de consulta no se están cargando el tipo y el nombre del área de consulta, tampoco en la tama `feature/compensationBug`.

En el módulo de compensación ambiental, en la rama `feature/compensationBug` al seleccionar un proyecto se está cambiando el nombre en el header, pero no está cambiando ni el mapa ni el panel de la derecha, se queda pegado en el selector. En `develop` se logra reproducir el error documentado por Hache después de intentar seleccionar un proyecto

**Comment by cazapatamar** [comment]
En mi ambiente local tengo el mismo comportamiento de Erika. Al estar sobre la rama ´feature/compensationBug´, al seleccionar un proyecto en compensaciones, si se setea el header pero se queda pegado y no avanza. Aparecen estos mensajes en la consola:

<img width="1740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlB4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba9da5c926c150addd0bd5743cd9291da7f243dc/imagen.png" alt="imagen.png" />

En el módulo de consultas parece todo andar bien.
