### ISSUE TITLE
Actualizar versión de axios

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#895]
## Descripción: 

Luego de ejecurtar ´yarn npm audit --all´ se encuentra que axios debe ser actualizada ya que existen vulnerabilidades en la version actual de biotablero.

├─ axios: 0.27.2
│  ├─ Issue: Axios Cross-Site Request Forgery Vulnerability
│  ├─ URL: https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
│  ├─ Severity: moderate
│  ├─ Vulnerable Versions: >=0.8.1 <1.6.0
│  ├─ Patched Versions: >=1.6.0
│  ├─ Via: axios
│  └─ Recommendation: Upgrade to version 1.6.0 or later

### Resultado:

Axios en la version >=1.6.0

## Consideraciones:

 Realizar multiples pruebas sobre todos los endpoints en todos los modulos

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/895?planning-poker) with Zenhub @hacheG @ManuelStardust

**Comment by hacheG** [comment]
se hizo la actualización  de axios a la versión 1.6.5, Camilo comento que hubo un problema en su equipo con esta actualización pero se soluciono
