### ISSUE TITLE
Actualizar versiones de dependencias indirectas

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#897]
## Descripción: 

Actualizar versiones de dependencias indirectas usando ´yarn-audit-fix´ como se hizo en una ocasion anterior. Priorizar sobre las vulnerabilidades criticas y altas.

Las vulnerabilidades se encuentran ejecutando el comando ´yarn npm audit --all --recursive´.

### Resultado:

Dependencias actualizadas.

## Consideraciones:

Dejar la menor cantidad de vulnerabilidades.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/897?planning-poker) with Zenhub @erikasv @hacheG @ManuelStardust

**Comment by erikasv** [comment]
La tarea se desvió a cambiar el manejador de paquetes por todas las restricciones que hay con yarn. Probamos pnpm pero hay que hacer varios ajustes, se discutirá con mayor profundidad el martes en reunión de linea con cuál nos quedamos. Se cambia la estimación por el cambio de alcance

**Comment by erikasv** [comment]
Al final de la semana pasada había quedado en que se logró hacer el cambio a pnpm, Hay un error del ResizeObserver que no sé de dónde salió ni cómo resolver, cuando pruebe en el modo producción determino si es grave o lo sigo ocultando. 

Para esta semana queda pendiente ajustar el dockerfile y los actions de github, mientras, esta es la rama con los cambios: https://github.com/PEM-Humboldt/biotablero-frontend/tree/feature/updateDeps
