### ISSUE TITLE
Limpiar mapa cuando se ingresa polígono

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#900]
## Descripción:

Luego de consultar la capa nacional (deptos, subzonas, CARs) se debe limpiar el mapa cuando se dibuja el polígono

<img width="1268" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWppQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d2971fe32507fe06c4556f0960ef0a8e1fcad52/imagen.png" alt="imagen.png" />

<img width="1197" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXJpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f648aa1da3c75f1be4121070e8d65a96687d274c/imagen.png" alt="imagen.png" />

### Resultado:

Bug arreglado

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/900?planning-poker) with Zenhub @erikasv @hacheG @ManuelStardust

**Comment by hacheG** [comment]
se arreglo el bug, ahora al entrar a la sección Dibujar polígono se limpia el mapa de la silueta rosada, si se había consultado previamente alguna área de consulta. Sin embargo, se muestra un error no bloqueante, ni que rompe la aplicación 
<img width="1734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGYyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db9756a46cb90f38e9e9cdaf1dad60d240eaa712/image.png" alt="image.png" />

una posible explicación seria que se espera hacer un trazo y no se realiza, al estar hasta ahora preparándose para hacer el poligono. Contexto: https://www.w3.org/TR/SVG2/paths.html
