### ISSUE TITLE
Release y Ajustes visuales

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-frontend#908]
## Descripción:

Hacer release.

1. Crear la rama release con la versión correspondiente y hacer el primer commit con el cambio de versión en el package.json.

Después, hacer los siguientes ajustes:

- Cambiar el correo de Maria C por el de biotablero en la parte de contacto
- Cambiar el link del SIAC en el footer (Confirmar con equipo temático)
- Actualizar feature flags de staging
- Sugerencia: Hacer que el cursor se cambie en la forma de la manito para que sea mas intuitivo el clic (Validar con Cesar).

2. Al último commit aprobar el despliegue en azure y verificar que el ambiente se desplegue correctamente

3. Actualizar producción

# Consideraciones

Revisar el [flujo de release](https://docs.google.com/document/d/1TGc0AX6aIhxKNArgszvij6KRoHZ0uYSzuTMfRvDDO-E/edit#heading=h.g4tehkkzm3e4) y actualizarlo en caso de que sea necesario.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/908?planning-poker) with Zenhub @erikasv @hacheG @ManuelStardust

**Comment by erikasv** [comment]
@cazapatamar @ManuelStardust @hacheG Reestimar la tarea, ahora incluye el despliegue
