### ISSUE TITLE
[Spike] Mejorar cambio de capas para pérdida y persistencia

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#914]
# Descripción

Buscar una mejor forma de organizar la lógica para el control de las capas en el mapa, considerar varias opciones, por ejemplo:

- Que los acordeones se hablen cada uno directamente con mapviewer, o
- que cada pestaña sea un componente grande que tenga su mapviewer, o 
- una nueva función que aparentemente sea más fácil de entender y manejar para el cambio de capas, etc

Citar un espacio de media hora el viernes para discutir ideas tempranas.

**Comment by ManuelStardust** [comment]
Se generó el siguiente diagrama con el flujo actual para el manejo de capas y la propuesta de modificación para este flujo: https://drive.google.com/file/d/1Vp0CBVq92weLv2fwMCmLSgtl9rkv_YA4/view?usp=sharing
