### ISSUE TITLE
Pruebas sobre nueva implementación de capas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-frontend#919]
# Descripción

Sobre la rama [migrateSwitchLayer](https://github.com/PEM-Humboldt/biotablero-frontend/tree/migrateSwitchLayer) del front hacer los ajustes necesarios para procesar las capas de pérdida y persistencia con la implementación de [adjustmentCropRaster](https://github.com/PEM-Humboldt/biotablero-search-backend/tree/adjustmentCropRaster) en el backend.

Probar con áreas grandes, por ahí del tamaño de meta, para verificar que no hayan problemas de rendimiento, registrar en esta tarea el polígono con el que se probó y el peso de la respuesta del backend.

# Actualización 16/10/2024
Se  decide hacer una implementación con compresión de acuerdo a los resultados del sprint anterior

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-frontend/919?planning-poker) with Zenhub @denarch22

**Comment by denarch22** [comment]
Realice el ajuste de consumir del back los base64 para el front, tuve que realizar un ajuste adicional ya que estaba teniendo inconvenientes con los request ya me decía que método no permitido, pero ya funciona, realice pruebas con polígonos pequeños y polígonos mas grandes como el departamento de Meta, aunque la respuesta es mas demorada por el tamaño funciona bien el peso de la capa no es tan grande.

**Comment by denarch22** [comment]
Estuve realizando las correcciones al MR de stac data tools y continue con la tarea de la compresión, identifique varios escenarios, la compresión en este caso es del cambio de formato del raster , puede ser en png, wepb , jpeg u otros y después si pasarlos a base64, el inconveniente es el costo de esa transformación, png es el mas rápido con 1,7 min, y deja un peso por capa de 29mb, webp es otro formato compatible en el navegador y aunque comprime a 22mb su conversión es muy demorada siendo de 6m, por lo que lo descarte y jpeg, es otro formato pero no maneja imágenes simples sino que maneja características RGB que aumentan el detalle

**Comment by denarch22** [comment]
Según la reunión realizada el día de hoy, se realizara la división de las imágenes por categoría , lo que quiere decir que el front llamara cada capa por categoría.

**Comment by denarch22** [comment]
Según la prueba solicitada se evidencio que aunque la conversión en base64 se realice en el front o en el back se demora y pesa las imágenes casi que lo mismo, en el tiempo puede influir el internet, se deja evidencia de lo indicado:<img width="1726" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzk4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--510e6e1d18bd24a5cf0be79dbcda58b8b039802d/image.png" alt="image.png" />
